CREATE TABLE "EWALLET_V21"."ACCOUNT_BALANCE_CHANGE_BK" 
   (	"BALANCE_CHANGE_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"ACCOUNT_ID" NUMBER(22,0), 
	"TRANSACTION_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"ACTION_ID" NUMBER(22,0), 
	"TRANS_ACCOUNTING_ID" NUMBER(22,0), 
	"PROCESS_CODE" VARCHAR2(6) NOT NULL ENABLE, 
	"TRANS_TYPE_ID" NUMBER(10,0), 
	"AMOUNT" NUMBER(30,5) NOT NULL ENABLE, 
	"CURRENCY_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"DIRECTION" NUMBER(2,0) NOT NULL ENABLE, 
	"BEFORE_BALANCE" NUMBER(30,5), 
	"AFTER_BALANCE" NUMBER(30,5), 
	"DATE_CREATED" DATE NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

