CREATE TABLE "EWALLET_V21"."ACCOUNT_RIGHT_DEFAULT_20190813" 
   (	"ACCOUNT_RIGHT_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"PROCESS_CODE" VARCHAR2(6) NOT NULL ENABLE, 
	"ROLE_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"ACCOUNT_STATE_ID" NUMBER(5,0), 
	"TRANSACTION_TYPE_ID" NUMBER(2,0), 
	"ACCOUNT_TYPE_ID" NUMBER(5,0), 
	"CREATED_BY" VARCHAR2(50), 
	"MODIFIED_BY" VARCHAR2(50), 
	"CREATED_TIME" DATE, 
	"LAST_MODIFIED" DATE, 
	"STATUS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

