CREATE TABLE "EWALLET_V21"."ACCOUNT_STATUS_VIEW_BK" 
   (	"ACCOUNT_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"CODE" VARCHAR2(30), 
	"ROLE_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"ROLE_NAME" VARCHAR2(50), 
	"PARTY_ROLE_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"PARTY_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(50), 
	"LAST_NAME" VARCHAR2(100), 
	"GENDER" NVARCHAR2(20), 
	"BIRTHDAY" DATE, 
	"TIN" VARCHAR2(20), 
	"ADDRESS" VARCHAR2(500), 
	"AREA_CODE" VARCHAR2(50), 
	"MSISDN" VARCHAR2(20), 
	"CURRENCY_CODE" VARCHAR2(3), 
	"PAPER_TYPE" VARCHAR2(4), 
	"PAPER_NUMBER" VARCHAR2(25) NOT NULL ENABLE, 
	"ISSUED_DATE" DATE, 
	"ISSUED_PLACE" VARCHAR2(50), 
	"EXPIRED_DATE" DATE, 
	"ACCOUNT_STATE_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"ACCOUNT_STATE_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"ACCOUNT_TYPE_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"ACCOUNT_TYPE_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"PAPER_NAME" VARCHAR2(30 CHAR), 
	"ACTIVE_TIME" DATE, 
	"DISTRINCT" VARCHAR2(50), 
	"SUBDISTRICT" VARCHAR2(50), 
	"SUKU" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

