CREATE TABLE "EWALLET_V21"."ACCOUNT_2" 
   (	"ACCOUNT_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"PAN" VARCHAR2(34), 
	"ACCOUNT_STATE_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"BALANCE" RAW(2000), 
	"ACCOUNT_TYPE_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"MODIFIED_DATE" TIMESTAMP (7), 
	"CURRENCY_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"PARTY_ROLE_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"CURRENCY" VARCHAR2(10), 
	"PARTITION_KEY" VARCHAR2(2), 
	"HOLDING_BALANCE" RAW(2000), 
	"AVAILABLE_BALANCE" RAW(2000), 
	"CREATED_DATE" TIMESTAMP (7), 
	"PIN" VARCHAR2(250), 
	"VPAN" VARCHAR2(50), 
	"LAST_RESET_PIN" DATE, 
	"IS_CURRENT" NUMBER(1,0), 
	"COUNT_QUERY_CASH" NUMBER(10,0), 
	"ACTIVE_TIME" DATE, 
	"LAST_TRANS_TIME" DATE, 
	"LAST_CHANGE_BALANCE_TIME" DATE, 
	"CURRENCY_CODE" VARCHAR2(5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

