CREATE TABLE "EWALLET_V21"."ACCOUNT_FOR_TARIFF_134264" 
   (	"ACCOUNT_ID" NUMBER, 
	"PROCESS_CODE" VARCHAR2(6), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"STATUS" NUMBER, 
	"CREATED_BY" VARCHAR2(50), 
	"CREATED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

