CREATE TABLE "EWALLET_V21"."ACTION_LOG" 
   (	"ACTION_ID" NUMBER(17,0) NOT NULL ENABLE, 
	"PROCESS_CODE" VARCHAR2(6), 
	"ACTION_NODE_ID" NUMBER(8,0), 
	"ACTION_STATE_ID" NUMBER(8,0), 
	"PAN" VARCHAR2(34), 
	"DATE_CREATED" DATE, 
	"LONGITUDE" NUMBER(25,20), 
	"LATITUDE" NUMBER(25,20), 
	"CARRIED_ACCOUNT_ID" NUMBER(12,0), 
	"DATE_FINISHED" DATE, 
	"PARTY_ROLE_ID" NUMBER(12,0), 
	"MIT" VARCHAR2(4), 
	"BITMAP" VARCHAR2(128), 
	"ORG_AMOUNT" NUMBER(30,5) DEFAULT 0, 
	"FROM_CURRENCY" VARCHAR2(5) DEFAULT '5', 
	"AMOUNT" NUMBER(30,5) DEFAULT 0, 
	"EXCHANGE_RATE" NUMBER(9,0) DEFAULT 1, 
	"STAN" VARCHAR2(11), 
	"DATE_EXPIRIED" DATE, 
	"DATE_APPROVED" DATE, 
	"STATUS_APPROVED" NUMBER(2,0), 
	"MERCHANT_TYPE" VARCHAR2(5), 
	"ROLE_ID" NUMBER(4,0), 
	"SENDER_AGENT" VARCHAR2(20), 
	"RECEIVER_AGENT" VARCHAR2(20), 
	"PHONE" VARCHAR2(20), 
	"RESPONE_CODE" VARCHAR2(5), 
	"RESPONE_DES" VARCHAR2(4000), 
	"SERVICE_CODE" VARCHAR2(10), 
	"CUS_NAME" VARCHAR2(51), 
	"CUS_BIRTHDAY" DATE, 
	"PAPER_TYPE" VARCHAR2(5), 
	"PAPER_NUMBER" VARCHAR2(30), 
	"ISSUED_DATE" DATE, 
	"EXP_DATE_PAPER" DATE, 
	"ISSUED_PLACE" VARCHAR2(50), 
	"CUS_ADDRESS" VARCHAR2(150), 
	"CUS_AREA" VARCHAR2(30), 
	"TIN" VARCHAR2(30), 
	"CUS_PHONE" VARCHAR2(20), 
	"TIER" NUMBER(3,0), 
	"PAYMENT_CODE" VARCHAR2(30), 
	"FROM_PHONE" VARCHAR2(20), 
	"TO_PHONE" VARCHAR2(20), 
	"FROM_NAME" VARCHAR2(50), 
	"TO_NAME" VARCHAR2(50), 
	"FROM_ACCOUNT" NUMBER(8,0), 
	"TO_ACCOUNT" NUMBER(8,0), 
	"INQUIRER" VARCHAR2(30), 
	"APPROVER" VARCHAR2(27), 
	"SERVICE_INDICATOR" VARCHAR2(10), 
	"TRAN_DES" VARCHAR2(1000), 
	"RECEIVER_AREA" VARCHAR2(30), 
	"RECEIVER_ADDRESS" VARCHAR2(50), 
	"CARRIED_CODE" VARCHAR2(20), 
	"CARRIED_NAME" VARCHAR2(100), 
	"REFERENCE_ID" NUMBER(15,0), 
	"LOCK_ID" NUMBER(15,0), 
	"REQUEST_ID" NVARCHAR2(30), 
	"FILE_NAME" VARCHAR2(100), 
	"MAC" VARCHAR2(50), 
	"LANG" VARCHAR2(5), 
	"FROM_DATE" DATE, 
	"TO_DATE" DATE, 
	"EFFECT_TYPE" VARCHAR2(30), 
	"TO_CURRENCY" VARCHAR2(5) DEFAULT '5', 
	"REQUEST_CONTENT" NVARCHAR2(2000), 
	"RESPONSE_CONTENT" NVARCHAR2(2000), 
	"BANK_TRANSID" VARCHAR2(50), 
	"BANK_CODE" VARCHAR2(50), 
	"BANK_NAME" VARCHAR2(50), 
	"BRANCH_BANK" VARCHAR2(50), 
	"BANK_ACCOUNT_NO" VARCHAR2(50), 
	"BANK_TIME" DATE, 
	"REQUEST_NO" VARCHAR2(50), 
	"CLIENT_IP" VARCHAR2(50), 
	"CUS_GENDER" NVARCHAR2(20), 
	"ACTION_TYPE_NAME" VARCHAR2(50), 
	"ACTION_STATE_NAME" VARCHAR2(50), 
	"RESPONSE_TIME" DATE, 
	"REQUEST_TIME" DATE, 
	 CONSTRAINT "PK_AAS" PRIMARY KEY ("ACTION_ID")
  USING INDEX PCTFREE 10 INITRANS 4 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
  PARTITION BY RANGE ("DATE_CREATED") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) 
 (PARTITION "LOG_DATA_P1"  VALUES LESS THAN (TO_DATE(' 2017-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ) ;

