CREATE TABLE "EWALLET_V21"."AGENT_POS_LOCKED" 
   (	"ID" NUMBER(22,0), 
	"AGENT_ID" NUMBER(12,0), 
	"FROM_DATE" DATE, 
	"TO_DATE" DATE, 
	"STATUS" NUMBER(2,0), 
	"REASON" VARCHAR2(200), 
	"REQUEST_ID" NUMBER, 
	"PUSH_ID" NUMBER, 
	"REASON_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

