CREATE TABLE "EWALLET_V21"."AGENT_LOCATION" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"AGENT_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"AGENT_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	"ROLE_ID" NUMBER(1,0), 
	"PHONE" VARCHAR2(50), 
	"LATITUDE" NUMBER(25,20), 
	"LONGITUDE" NUMBER(25,20), 
	"STATUS" NUMBER(2,0), 
	"CREATED_DATE" DATE, 
	"MODIFY_DATE" DATE, 
	"AGENT_ADDRESS" VARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

