CREATE TABLE "EWALLET_V21"."APP_PARAMS" 
   (	"PAR_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"PAR_TYPE" VARCHAR2(25), 
	"PAR_CODE" VARCHAR2(30), 
	"PAR_VALUE" VARCHAR2(200) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(250), 
	"STATUS" NUMBER(1,0) NOT NULL ENABLE, 
	"PAR_ORDER" NUMBER(2,0) NOT NULL ENABLE, 
	"LOCALE_KEY" VARCHAR2(50), 
	"CAN_RELOAD" NUMBER, 
	 PRIMARY KEY ("PAR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

