CREATE TABLE "EWALLET_V21"."APP_ERROR" 
   (	"ERROR_ID" NUMBER NOT NULL ENABLE, 
	"ERROR_CODE" VARCHAR2(10) NOT NULL ENABLE, 
	"ERROR_DESC" VARCHAR2(1024), 
	"SYSTEM_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

