CREATE TABLE "EWALLET_V21"."APP_FEATURE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"CONTENT_TE" VARCHAR2(1000), 
	"CONTENT_EN" VARCHAR2(1000), 
	"NOTIFICATION_EN" VARCHAR2(1000), 
	"NOTIFICATION_TE" VARCHAR2(1000), 
	"FROM_DATE" DATE, 
	"TO_DATE" DATE, 
	"NAME_CREATED" VARCHAR2(50), 
	"DATE_CREATED" DATE, 
	"STATUS_LOCK" NUMBER, 
	"DOCUMENT_LINK_EN" VARCHAR2(500), 
	"DOCUMENT_LINK_TE" VARCHAR2(500), 
	"VIDEO_LINK_EN" VARCHAR2(500), 
	"VIDEO_LINK_TE" VARCHAR2(500), 
	"ACTION_NODE_ID" NUMBER NOT NULL ENABLE, 
	"APP_TYPE" VARCHAR2(20) NOT NULL ENABLE, 
	"DATE_UPDATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

