CREATE TABLE "EWALLET_V21"."APP_USER_MENU_NEW" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"APP_USER_ID" NUMBER, 
	"MSISDN" VARCHAR2(20), 
	"CLIENT_TYPE" NUMBER(5,0), 
	"ADJUSTMENT_MENU_DATA" CLOB, 
	"RECENT_MENU_DATA" VARCHAR2(4000), 
	"CREATE_TIME" DATE DEFAULT SYSDATE, 
	"UPDATE_TIME" DATE, 
	 CONSTRAINT "APP_USER_MENU_NEW_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" 
 LOB ("ADJUSTMENT_MENU_DATA") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

