CREATE TABLE "EWALLET_V21"."AREA" 
   (	"AREA_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"AREA_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"AREA_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"AREA_TYPE" NUMBER(5,0), 
	"COUNTRY_CODE" VARCHAR2(3), 
	"PARENT_CODE" VARCHAR2(20), 
	"REGION_LEVEL_1" VARCHAR2(5), 
	"REGION_LEVEL_2" VARCHAR2(5), 
	"REGION_LEVEL_3" VARCHAR2(5), 
	"REGION_LEVEL_4" VARCHAR2(5), 
	"REGION_LEVEL_5" VARCHAR2(5), 
	"NUM_CHANNEL" NUMBER(8,0) DEFAULT 0, 
	"BRANCH" VARCHAR2(50), 
	 CONSTRAINT "AREA_PK" PRIMARY KEY ("AREA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

