CREATE TABLE "EWALLET_V21"."AUTO_PROCESS_MANAGER" 
   (	"PROCESS_ID" NUMBER(20,0), 
	"PROCESS_NAME" VARCHAR2(100), 
	"STATUS" VARCHAR2(100), 
	"START_DATE" DATE, 
	"FINISH_DATE" DATE, 
	"DESCRIPTION" VARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

