CREATE TABLE "EWALLET_V21"."BANK_ACCOUNT" 
   (	"BANK_ACCOUNT_ID" NUMBER NOT NULL ENABLE, 
	"BANK_MSISDN" VARCHAR2(20), 
	"BANK_ACCOUNT_NO" VARCHAR2(50), 
	"BANK_CARD_NO" VARCHAR2(50), 
	"BANK_BRANCH_NAME" VARCHAR2(100), 
	"BANK_ID" NUMBER, 
	"BANK_ACCOUNT_NAME" VARCHAR2(100), 
	"PARTY_ID" NUMBER, 
	"TYPE" VARCHAR2(20) DEFAULT 0, 
	 CONSTRAINT "BANK_ACCOUNT_INFO_PK" PRIMARY KEY ("BANK_ACCOUNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

