CREATE TABLE "EWALLET_V21"."CAPITAL_DETAIL" 
   (	"CAPITAL_DETAIL_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"CAPITAL_ID" NUMBER(22,0), 
	"AMOUNT" NUMBER(22,2), 
	"AMOUNT_BEFORE" NUMBER(22,2), 
	"AMOUNT_AFTER" NUMBER(22,2), 
	"DEBT_BEFORE" NUMBER(22,2), 
	"DEBT_AFTER" NUMBER(22,2), 
	"TRANS_TYPE_ID" NUMBER(22,0), 
	"TRANSACTION_ID" NUMBER(22,0), 
	 CONSTRAINT "CAPITAL_DETAIL_PK" PRIMARY KEY ("CAPITAL_DETAIL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

