CREATE TABLE "EWALLET_V21"."CASH_BACK_LOG" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ACC_ID" NUMBER(10,0), 
	"MSISDN" VARCHAR2(15), 
	"CREATED_DATE" DATE, 
	"TRANSACTION_ID" NUMBER(22,0), 
	"AMOUNT" NUMBER(10,2), 
	"STATUS" NUMBER(1,0), 
	"DESCRIPTION" VARCHAR2(500), 
	"ERROR_CODE" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

