CREATE TABLE "EWALLET_V21"."CATALOG_HIS_MAPPING" 
   (	"PROCESS_CODE" VARCHAR2(6), 
	"ROLE_ID" NUMBER(2,0), 
	"STATUS" NUMBER, 
	"CATALOG_ID" NUMBER, 
	"CATALOG_CODE" VARCHAR2(100), 
	"FUNCTION_CODE" VARCHAR2(100), 
	"FUNCTION_NAME" VARCHAR2(100), 
	"ITEM_CODE" VARCHAR2(100), 
	"ITEM_NAME" VARCHAR2(100), 
	"ACTION_NODE_ID" NUMBER, 
	"ORDER_NO" NUMBER, 
	"PARENT_ID" NUMBER, 
	"ITEM_LEVEL" NUMBER, 
	"CREATED_DATE" DATE, 
	"UPDATED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

