CREATE TABLE "EWALLET_V21"."CHANGE_STATE_ACTION_TEMP" 
   (	"ACCOUNT_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"ACTION_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"DATE_CREATED" DATE NOT NULL ENABLE, 
	"REASON_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"FROM_STATE" NUMBER(5,0), 
	"TO_STATE" NUMBER(5,0), 
	"CARRIED_ACCOUNT" NUMBER(12,0), 
	"FROM_PHONE" VARCHAR2(20), 
	"CARRIED_PHONE" VARCHAR2(20), 
	"CARRIED_CODE" VARCHAR2(20), 
	"CARRIED_NAME" VARCHAR2(50), 
	"REASON" VARCHAR2(100), 
	"LAST" NUMBER(1,0), 
	"TRANS_STATE_ID" VARCHAR2(3), 
	"PROCESS_CODE" VARCHAR2(6), 
	"TRANSACTION_ID" NUMBER(12,0), 
	"APPROVE_USER" VARCHAR2(50), 
	"APPROVE_DATE" DATE, 
	"APPROVE_NOTE" VARCHAR2(100), 
	"SERVICE_CODE" VARCHAR2(100), 
	"PAPER_TYPE" VARCHAR2(20), 
	"FILE_NAMES" VARCHAR2(1000), 
	"FEE" NUMBER, 
	"ACC_STATE_REQ" NUMBER, 
	"PAYMENT_CODE" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

