CREATE TABLE "EWALLET_V21"."CHANGE_INFO_ACTION" 
   (	"ACTION_ID" NUMBER(17,0) NOT NULL ENABLE, 
	"PROCESS_CODE" VARCHAR2(6), 
	"PHONE" VARCHAR2(20), 
	"PARTY_ROLE_ID" NUMBER(15,0), 
	"CARRIED_CODE" VARCHAR2(20), 
	"CARRIED_NAME" VARCHAR2(50 CHAR), 
	"CARRIED_PHONE" VARCHAR2(20), 
	"CARRIED_ACCOUNT_ID" NUMBER(15,0), 
	"REASON" VARCHAR2(500 CHAR), 
	"DATE_CREATED" DATE, 
	"ACTION_STATE_ID" NUMBER(8,0), 
	"TRANSACTION_ID" NUMBER(22,0), 
	"CHANGE_TYPE" VARCHAR2(30), 
	"OBJECT_ID" NUMBER, 
	"FROM_VALUE" VARCHAR2(50), 
	"TO_VALUE" VARCHAR2(50)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
  PARTITION BY RANGE ("DATE_CREATED") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) 
 (PARTITION "LOG_DATA_P1"  VALUES LESS THAN (TO_DATE(' 2017-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ) ;

