CREATE TABLE "EWALLET_V21"."COMISSION_SA_MA" 
   (	"ID" NUMBER, 
	"FROM_ACCOUNT" NUMBER, 
	"TO_ACCOUNT" NUMBER, 
	"FROM_PHONE" VARCHAR2(15), 
	"TO_PHONE" VARCHAR2(15), 
	"TYPE" VARCHAR2(50), 
	"AMOUNT" NUMBER(8,2), 
	"CONSUME_NON_W" NUMBER(8,2), 
	"CONSUME_ELECT" NUMBER(8,2), 
	"CONSUME_LOTERY" NUMBER(8,2), 
	"CONSUME_PULSA" NUMBER(8,2), 
	"FUNDING_AMOUNT" NUMBER(8,2), 
	"DEPOSIT_AMOUNT" NUMBER(8,2), 
	"CASHOUT_AMOUNT" NUMBER(8,2), 
	"REMAIN_AMOUNT" NUMBER(8,2), 
	"CREATE_DATE" DATE, 
	"DESCRIPTION" VARCHAR2(250), 
	"STATUS" NUMBER DEFAULT 0, 
	"TRANSACTION_ID" VARCHAR2(100), 
	"PROCESS_CODE" VARCHAR2(10), 
	"PROCESS_CODE_DES" VARCHAR2(100), 
	"HOUR_RUN" NUMBER DEFAULT 0, 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

