CREATE TABLE "EWALLET_V21"."COMPLAIN_TRANS" 
   (	"TRANSACTION_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"TRANS_TYPE_ID" NUMBER(10,0), 
	"TRANS_STATE_ID" NUMBER(10,0), 
	"CARRIED_PHONE" NVARCHAR2(20), 
	"CARRIED_CODE" NVARCHAR2(100), 
	"TOTAL_AMOUNT" NUMBER(30,5), 
	"COMPLAIN_TRANS_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"COMPLAIN_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"REQUEST_TYPE" NUMBER(1,0), 
	"STATUS" NUMBER(1,0), 
	"AMOUNT" NUMBER(30,5), 
	 CONSTRAINT "COMPLAIN_TRANS_PK" PRIMARY KEY ("COMPLAIN_TRANS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

