CREATE TABLE "EWALLET_V21"."COMPLAIN_AUDIT_LOG" 
   (	"COMPLAIN_AUDIT_LOG_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"ACCOUNT_CODE" NVARCHAR2(100), 
	"ACCOUNT_NAME" NVARCHAR2(100), 
	"DATE_CREATED" DATE, 
	"ACTION" NUMBER(10,0), 
	"IP" NVARCHAR2(100), 
	"REASON_CONTENT" NVARCHAR2(2000), 
	"IS_FILE_ATTACH" NUMBER(1,0), 
	"COMPLAIN_TRANS_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"ERROR_CODE" VARCHAR2(10), 
	"ERROR_DES" NVARCHAR2(250), 
	 CONSTRAINT "COMPLAIN_AUDIT_LOG_PK" PRIMARY KEY ("COMPLAIN_AUDIT_LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

