CREATE TABLE "EWALLET_V21"."COMPLAIN" 
   (	"PHONE" NVARCHAR2(100), 
	"COMPLAIN_STATE" NUMBER(1,0), 
	"COMPLAIN_CONTENT" NVARCHAR2(2000), 
	"USER_CREATED" NVARCHAR2(100), 
	"DATE_CREATED" DATE, 
	"RESULT_CONTENT" NVARCHAR2(2000), 
	"USER_APPROVAL" NVARCHAR2(100), 
	"DATE_APPROVAL" DATE, 
	"COMPLAIN_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"REASON_ID" NUMBER(22,0), 
	 CONSTRAINT "COMPLAIN_PK" PRIMARY KEY ("COMPLAIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

