CREATE TABLE "EWALLET_V21"."CONFIG_SHORT_CODE_PACKAGE" 
   (	"ID" NUMBER(22,0), 
	"PACKAGE_CODE" VARCHAR2(10) NOT NULL ENABLE, 
	"SHORT_CODE" VARCHAR2(10) NOT NULL ENABLE, 
	"STATUS" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"CREATED_DATE" DATE, 
	"PACKAGE_TYPE" VARCHAR2(10) NOT NULL ENABLE, 
	 CONSTRAINT "PK_CONFIG_SHORT_CODE_PACKAGE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

