CREATE TABLE "EWALLET_V21"."CONFIG_AGENT_NETWORK" 
   (	"ID" NUMBER(10,0), 
	"FROM_PHONE" VARCHAR2(15), 
	"TO_PHONE" VARCHAR2(15), 
	"FROM_ACC_ID" NUMBER(10,0), 
	"TO_ACC_ID" NUMBER(10,0), 
	"DATE_CREATED" DATE, 
	"STATUS" NUMBER(1,0), 
	"PROCESS_CODE" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

