CREATE TABLE "EWALLET_V21"."CONFIG_BYPASS_BY_BIOMETRICS" 
   (	"ID" NUMBER, 
	"PROCESS_CODE" VARCHAR2(50), 
	"SERVICE_CODE" VARCHAR2(100), 
	"PARTNER_CODE" VARCHAR2(100), 
	"ACCOUNT_ID" NUMBER, 
	"STATUS" VARCHAR2(100), 
	"ACTION_ID" NUMBER, 
	"REASON" VARCHAR2(100), 
	"VERSION" VARCHAR2(100), 
	"DEVICE_ID" VARCHAR2(200), 
	"CREATED_DATE" DATE, 
	"UPDATED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

