CREATE TABLE "EWALLET_V21"."CONTACT_MEDIUM" 
   (	"CONTACT_MEDIUM_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"MEDIUM_TYPE" NUMBER(5,0), 
	"CONTACT_ADDRESS" VARCHAR2(50), 
	 CONSTRAINT "PK_CMM" PRIMARY KEY ("CONTACT_MEDIUM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

