CREATE TABLE "EWALLET_V21"."CURRENCY" 
   (	"CURRENCY_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"CURRENCY" VARCHAR2(100), 
	"CURRENCY_CODE" VARCHAR2(3), 
	"CURRENCY_NUM_CODE" VARCHAR2(3), 
	"MINOR_UNIT" NUMBER(1,0), 
	"USED" NUMBER(2,0), 
	"CURRENCY_SYMBOL" VARCHAR2(5), 
	"CURRENCY_DECIMAL" VARCHAR2(10), 
	 CONSTRAINT "PK_CY" PRIMARY KEY ("CURRENCY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

