CREATE TABLE "EWALLET_V21"."CUS_PAY_BENEFITS" 
   (	"CUS_ID" NUMBER DEFAULT NULL NOT NULL ENABLE, 
	"ID_NUMBER" VARCHAR2(20) NOT NULL ENABLE, 
	"ID_TYPE" VARCHAR2(10), 
	"STATUS" NUMBER(5,0), 
	"FULL_NAME" VARCHAR2(100), 
	"BIRTHDAY" DATE, 
	"GENDER" NVARCHAR2(20), 
	"ADDRESS" VARCHAR2(500), 
	"CREATED_DATE" TIMESTAMP (7), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(50), 
	"MODIFY_BY" VARCHAR2(50), 
	"AMOUNT" NUMBER(5,2), 
	"AGE" NUMBER(3,0), 
	"PAYMENT_ERR" VARCHAR2(20), 
	"PAYMENT_DES" VARCHAR2(2000), 
	"TRANS_ID" VARCHAR2(22)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

