CREATE TABLE "EWALLET_V21"."CUSTOMER_REGISTER_TEMP" 
   (	"CUSTOMER_PHONE" VARCHAR2(20) NOT NULL ENABLE, 
	"CUSTOMER_NAME" VARCHAR2(100), 
	"CUSTOMER_BIRTHDAY" DATE, 
	"CUSTOMER_GENDER" NVARCHAR2(20), 
	"PAPER_TYPE" VARCHAR2(4), 
	"PAPER_NUMBER" VARCHAR2(20) NOT NULL ENABLE, 
	"AREA" VARCHAR2(50), 
	"ADDRESS" VARCHAR2(500), 
	"CHANNEL_CODE" VARCHAR2(50), 
	"CHANNEL_NAME" VARCHAR2(100), 
	"ID_CC" VARCHAR2(50), 
	"REASON" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

