CREATE TABLE "EWALLET_V21"."DEVICE_INFO_MANAGE" 
   (	"ID" NUMBER, 
	"DEVICE_ID" VARCHAR2(100), 
	"BLOCK_TIME" NUMBER, 
	"BLOCKING_DATE" DATE, 
	"LAST_LOGIN_DATE" DATE, 
	"LAST_LOGIN_USER" VARCHAR2(20), 
	"FAIL_TIME_OTP" NUMBER, 
	"FAIL_TIME_PIN" NUMBER, 
	"ROLE_ID" NUMBER, 
	"VERSION" VARCHAR2(20), 
	"MSISDN" VARCHAR2(20), 
	"BLOCKING_DATE_SENT_OTP" DATE, 
	"NUMBER_SENT_OTP" NUMBER DEFAULT 0, 
	 CONSTRAINT "DEVICE_INFO_MANAGE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

