CREATE TABLE "EWALLET_V21"."DIRECTION" 
   (	"TRANSACTION_TYPE_ID" NUMBER(8,0), 
	"NAME" VARCHAR2(20), 
	"LOCALE_KEY" VARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

