CREATE TABLE "EWALLET_V21"."EMAIL_CONTENT_SUBJECT" 
   (	"CONFIG_ID" NUMBER DEFAULT NULL NOT NULL ENABLE, 
	"EMAIL_ID" NUMBER, 
	"CONTENT_TEMPLATE" VARCHAR2(1000), 
	"SUBJECT_TEMPLATE" VARCHAR2(1000), 
	"CONTENT_SQL" VARCHAR2(500), 
	"SUBJECT_SQL" VARCHAR2(500), 
	"DATE_CREATED" DATE DEFAULT (sysdate), 
	 PRIMARY KEY ("CONFIG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

