CREATE TABLE "EWALLET_V21"."EMAIL_COMMON_CONFIG" 
   (	"EMAIL_ID" NUMBER DEFAULT NULL NOT NULL ENABLE, 
	"LIST_TO" VARCHAR2(1000), 
	"LIST_CC" VARCHAR2(1000), 
	"LIST_BCC" VARCHAR2(1000), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"STATUS" NUMBER, 
	"DATE_CREATED" DATE, 
	"CREATED_BY" VARCHAR2(100), 
	 PRIMARY KEY ("EMAIL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

