CREATE TABLE "EWALLET_V21"."EMAIL_FILE_ATTACHMENT" 
   (	"CONFIG_ID" NUMBER DEFAULT NULL NOT NULL ENABLE, 
	"EMAIL_ID" NUMBER, 
	"PATH_XML" VARCHAR2(500), 
	"PATH_TEMPLATE" VARCHAR2(500), 
	"END_POINT" VARCHAR2(500), 
	"FILE_NAME" VARCHAR2(300), 
	 PRIMARY KEY ("CONFIG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

