CREATE TABLE "EWALLET_V21"."GUIDE_LINE_LOG" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"MSISDN" VARCHAR2(20) NOT NULL ENABLE, 
	"CREATE_DATE" DATE, 
	"UPDATE_DATE" DATE, 
	"STATUS" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"ERR_CODE" VARCHAR2(50), 
	"ERR_DES" VARCHAR2(500), 
	"REQ_ID" VARCHAR2(50), 
	"BUY_ELECTRIC_G" NUMBER(1,0), 
	"BUY_DATA_G" NUMBER(1,0), 
	"BUY_PULSA_G" NUMBER(1,0), 
	"FIND_AGENT_G" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

