CREATE TABLE "EWALLET_V21"."INVOICE" 
   (	"INVOICE_ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(20) NOT NULL ENABLE, 
	"ACCOUNT_ID" NUMBER(22,0), 
	"PARTY_ROLE_ID" VARCHAR2(22), 
	"ADDRESS" VARCHAR2(500), 
	"BEFORE_TAX_AMOUNT" NUMBER(30,5) NOT NULL ENABLE, 
	"TAX" NUMBER(30,5), 
	"INVOICE_TYPE" NUMBER(2,0) NOT NULL ENABLE, 
	"PAYMENT_METHOD" NUMBER(2,0), 
	"INVOICE_DATE" DATE NOT NULL ENABLE, 
	"DATE_CREATED" DATE, 
	"DATE_MODIFIED" DATE, 
	"CREATED_BY" VARCHAR2(50) NOT NULL ENABLE, 
	"TRANSACTION_ID" NUMBER(22,0), 
	"ROLE_ID" NUMBER(2,0), 
	"TAX_RATE" NUMBER(30,5), 
	"CURRENCY" VARCHAR2(20) NOT NULL ENABLE, 
	"AFTER_TAX_AMOUNT" NUMBER(30,5), 
	"INVOICE_NO" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "INVOICE_PK" PRIMARY KEY ("INVOICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

