CREATE TABLE "EWALLET_V21"."ISO_MAPPING_CONFIG" 
   (	"TABLE_NAME" VARCHAR2(100), 
	"TABLE_FIELD" VARCHAR2(100), 
	"ISO_FIELD" VARCHAR2(100), 
	"PROCESS_CODE" VARCHAR2(20)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

