CREATE TABLE "EWALLET_V21"."LOG_TRANS_COMPLETED" 
   (	"TRANSACTION_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"FROM_ACC_ID" NUMBER(22,0), 
	"FROM_PHONE" VARCHAR2(20), 
	"FROM_NAME" VARCHAR2(250), 
	"FROM_PARTY_ROLE_ID" VARCHAR2(22), 
	"TO_ACC_ID" NUMBER(22,0), 
	"TO_PHONE" VARCHAR2(20), 
	"TO_NAME" VARCHAR2(250), 
	"TO_PARTY_ROLE_ID" NUMBER(22,0), 
	"AMOUNT" NUMBER(30,5) DEFAULT 0, 
	"DISCOUNT" NUMBER(30,5) DEFAULT 0, 
	"FEE" NUMBER(30,5) DEFAULT 0, 
	"COMMISSION" NUMBER(30,5) DEFAULT 0, 
	"TOTAL_AMOUNT" NUMBER(30,5) DEFAULT 0, 
	"REVENUE_SHARED" NUMBER(30,5) DEFAULT 0, 
	"CURRENCY" VARCHAR2(3) DEFAULT 840, 
	"TRANS_TYPE_ID" NUMBER(22,0), 
	"TRANSACTION_STATE_ID" NUMBER(22,0), 
	"ACTION_NODE_ID" NUMBER(8,0), 
	"CARRIED_NAME" VARCHAR2(250), 
	"CARRIED_ACC_ID" NUMBER(22,0), 
	"CARRIED_CODE" VARCHAR2(50), 
	"REASON_ID" NUMBER(22,0), 
	"CONTENT" NVARCHAR2(2000), 
	"REASON_CONTENT" NVARCHAR2(500), 
	"PARTNER_ID" NUMBER(22,0), 
	"DATE_CREATED" DATE, 
	"DATE_MODIFIED" DATE, 
	"DATE_EXPIRIED" DATE, 
	"DATE_DEADLINE" DATE, 
	"DATE_FINISHED" DATE, 
	"TARIFF_PLAN_ID" NUMBER(10,0), 
	"CARRIED_PHONE" VARCHAR2(20), 
	"DATE_CREATED_INT" NUMBER(8,0), 
	 CONSTRAINT "LOG_TRANS_COMPLETED_PK" PRIMARY KEY ("TRANSACTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

