CREATE TABLE "EWALLET_V21"."LOG_BUY_PACKAGE" 
   (	"ID" NUMBER(10,0), 
	"MSISDN" VARCHAR2(15), 
	"PACKAGE" VARCHAR2(100), 
	"BONUS" VARCHAR2(30), 
	"TYPE" VARCHAR2(30), 
	"DATE_CREATED" DATE, 
	"STATUS" NUMBER(1,0), 
	"ERR_TYPE" VARCHAR2(50), 
	"ERR_CODE" VARCHAR2(50), 
	"ERR_DES" VARCHAR2(1024), 
	"REQUEST" VARCHAR2(1024), 
	"RESPONSE" VARCHAR2(4000), 
	"TRANS_ID" VARCHAR2(50), 
	"REQ_ID" VARCHAR2(50)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
  PARTITION BY RANGE ("DATE_CREATED") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) 
 (PARTITION "LOG_DATA_P1"  VALUES LESS THAN (TO_DATE(' 2020-04-26 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" , 
 PARTITION "LOG_DATA_P2"  VALUES LESS THAN (TO_DATE(' 2020-04-27 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ) ;

