CREATE TABLE "EWALLET_V21"."LOG_EXECUTIVE_BUSINESS_REPORT2" 
   (	"LOG_ID" NUMBER DEFAULT "EWALLET_V21"."ISEQ$$_107395"."NEXTVAL" NOT NULL ENABLE, 
	"CATAGORY_CODE" NUMBER, 
	"LOG_DATE" DATE, 
	"LOG_DATE_INT" NUMBER, 
	"VALUE" NUMBER, 
	"TYPE" VARCHAR2(10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

