CREATE TABLE "EWALLET_V21"."LOG_COMMISSION_BY_TRANS_TYPE2" 
   (	"ROLE_ID" NUMBER, 
	"PROCESS_CODE" VARCHAR2(6), 
	"PROCESS_CODE_NAME" VARCHAR2(100), 
	"TRANS_TYPE_ID" NUMBER, 
	"TRANS_TYPE_NAME" VARCHAR2(200), 
	"TOTAL_COMMISSION" NUMBER, 
	"LOG_DATE" DATE, 
	"LOG_DATE_INT" NUMBER, 
	"LOG_MONTH_INT" NUMBER, 
	"LOG_YEAR_INT" NUMBER, 
	"NUMBER_OF_TRANSACTION" NUMBER, 
	"CURRENCY" VARCHAR2(6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

