CREATE TABLE "EWALLET_V21"."LOG_TYPE" 
   (	"LOG_TYPE_ID" NUMBER NOT NULL ENABLE, 
	"LOG_DES" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "LOG_TYPE_PK" PRIMARY KEY ("LOG_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

