CREATE TABLE "EWALLET_V21"."LOG_SEND_API" 
   (	"ID" NUMBER(10,0), 
	"MSISDN" VARCHAR2(15), 
	"USER_NAME" VARCHAR2(100), 
	"DATE_CREATED" DATE, 
	"STATUS" NUMBER(1,0), 
	"ERR_CODE" NUMBER(5,0), 
	"ERR_DES" VARCHAR2(1024), 
	"REQUEST" VARCHAR2(4000), 
	"RESPONSE" VARCHAR2(4000), 
	"API_NAME" VARCHAR2(500)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
  PARTITION BY RANGE ("DATE_CREATED") INTERVAL (NUMTOYMINTERVAL(1, 'MONTH')) 
 (PARTITION "LOG_DATA_P1"  VALUES LESS THAN (TO_DATE(' 2025-06-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" , 
 PARTITION "LOG_DATA_P2"  VALUES LESS THAN (TO_DATE(' 2025-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ) ;

