CREATE TABLE "EWALLET_V21"."LOG_MASTER_ACCOUNT_AUDIT2" 
   (	"ACCOUNT_ID" NUMBER NOT NULL ENABLE, 
	"OPENING_BALANCE" NUMBER, 
	"TOTAL_CREDIT" NUMBER, 
	"TOTAL_DEBIT" NUMBER, 
	"CLOSING_BALANCE" NUMBER, 
	"ACCOUNT_CODE" VARCHAR2(100), 
	"ACCOUNT_NAME" VARCHAR2(100), 
	"LOG_DATE" DATE NOT NULL ENABLE, 
	"ACCOUNT_TYPE_ID" NUMBER, 
	"CURRENCY_CODE" VARCHAR2(5), 
	"CREATED_DATE" DATE, 
	"LOG_DATE_INT" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

