CREATE TABLE "EWALLET_V21"."LOG_TABLE_CHANGES_CAPTURE" 
   (	"TABLE_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"ID_COLUMN_VALUE" VARCHAR2(100) NOT NULL ENABLE, 
	"ID_COLUMN_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"DATE_MODIFIER" TIMESTAMP (6) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(2000), 
	"STATUS_RECORD" VARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS  LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
  PARTITION BY RANGE ("DATE_MODIFIER") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) 
 (PARTITION "P20230902"  VALUES LESS THAN (TIMESTAMP' 2023-09-02 00:00:00') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ) ;

