CREATE TABLE "EWALLET_V21"."LOG_COUNT_CASH_OUT_FREE" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"STATUS" NUMBER(1,0), 
	"CREATE_DATE" DATE, 
	"PROCESS_CODE" VARCHAR2(50), 
	"MSISDN" VARCHAR2(30), 
	"REV_MONEY" NUMBER(10,2), 
	"CASHOUT_MONEY" NUMBER(10,2), 
	"TRANSACTION_ID" VARCHAR2(50), 
	"DESCRIPTION" VARCHAR2(300), 
	"CASHOUT_NUM" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

