CREATE TABLE "EWALLET_V21"."LOG_BONUS_DB_MOSAN" 
   (	"ID" NUMBER(10,0), 
	"MSISDN" VARCHAR2(15), 
	"METER_NUMBER" VARCHAR2(15), 
	"BUY_AMOUNT" NUMBER(5,2), 
	"BONUS_AMOUNT" NUMBER(5,2), 
	"TYPE" VARCHAR2(30), 
	"DATE_CREATED" DATE, 
	"STATUS" NUMBER(1,0), 
	"ERR_CODE" VARCHAR2(50), 
	"ERR_DES" VARCHAR2(1024), 
	"TRANS_ID" NUMBER(12,0), 
	"TRANS_BUY_ID" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

