CREATE TABLE "EWALLET_V21"."MASTER_ACCOUNT_STACK" 
   (	"STACK_ID" NUMBER NOT NULL ENABLE, 
	"ACCOUNT_ID" NUMBER NOT NULL ENABLE, 
	"BALANCE" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE DEFAULT (sysdate) NOT NULL ENABLE, 
	"STATUS" NUMBER, 
	"STACK_TYPE" NUMBER, 
	 CONSTRAINT "MASTER_ACCOUNT_STACK_PK" PRIMARY KEY ("STACK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

