CREATE TABLE "EWALLET_V21"."MASTER_ACCOUNT_STACK_CHANGE" 
   (	"BALANCE_CHANGE_ID" NUMBER NOT NULL ENABLE, 
	"STACK_ID" NUMBER NOT NULL ENABLE, 
	"TRANSACTION_ID" NUMBER, 
	"ACTION_ID" NUMBER, 
	"TRANS_ACCOUNTING_ID" NUMBER, 
	"PROCESS_CODE" VARCHAR2(6), 
	"TRANS_TYPE_ID" NUMBER, 
	"CURRENCY_CODE" VARCHAR2(3), 
	"AMOUNT" NUMBER, 
	"DIRECTION" NUMBER, 
	"BEFORE_BALANCE" NUMBER, 
	"AFTER_BALANCE" NUMBER, 
	"DATE_CREATED" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"IS_UPDATE_TO_MASTER_ACCOUNT" NUMBER DEFAULT 0, 
	"CONTENT" VARCHAR2(1000), 
	 CONSTRAINT "MA_STACK_BALANCE_CHANGE_PK" PRIMARY KEY ("BALANCE_CHANGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

