CREATE TABLE "EWALLET_V21"."MASTER_ACCOUNT" 
   (	"ACCOUNT_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"PAN" VARCHAR2(34), 
	"ACCOUNT_STATE_ID" NUMBER(5,0), 
	"BALANCE" NUMBER(30,5) DEFAULT 0, 
	"ACCOUNT_TYPE_ID" NUMBER(5,0), 
	"MODIFIED_DATE" DATE, 
	"CURRENCY_ID" NUMBER(8,0), 
	"CURRENCY" VARCHAR2(10), 
	"HOLDING_BALANCE" NUMBER(30,5) DEFAULT 0, 
	"AVAILABLE_BALANCE" NUMBER(30,5) DEFAULT 0, 
	"CREATED_DATE" DATE, 
	"PIN" VARCHAR2(250), 
	"V_PAN" VARCHAR2(50), 
	"NAME" VARCHAR2(100), 
	"CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"CURRENCY_CODE" VARCHAR2(5), 
	"CREATED_BY" VARCHAR2(30), 
	"IS_CONTAIN_STACK" NUMBER, 
	"PARENT_ACCOUNT_ID" NUMBER, 
	"IS_CONTAIN_CHILD_ACCOUNT" NUMBER, 
	 CONSTRAINT "MASTER_ACCOUNT_PK_NEW" PRIMARY KEY ("ACCOUNT_ID")
  USING INDEX PCTFREE 30 INITRANS 8 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 30 PCTUSED 0 INITRANS 4 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

