CREATE TABLE "EWALLET_V21"."MASTER_ACCOUNT_20190813" 
   (	"ACCOUNT_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"PAN" VARCHAR2(34), 
	"ACCOUNT_STATE_ID" NUMBER(5,0), 
	"BALANCE" NUMBER(30,5), 
	"ACCOUNT_TYPE_ID" NUMBER(5,0), 
	"MODIFIED_DATE" DATE, 
	"CURRENCY_ID" NUMBER(8,0), 
	"CURRENCY" VARCHAR2(10), 
	"HOLDING_BALANCE" NUMBER(30,5), 
	"AVAILABLE_BALANCE" NUMBER(30,5), 
	"CREATED_DATE" DATE, 
	"PIN" VARCHAR2(250), 
	"V_PAN" VARCHAR2(50), 
	"NAME" VARCHAR2(100), 
	"CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"CURRENCY_CODE" VARCHAR2(5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

