CREATE TABLE "EWALLET_V21"."MERCHANT" 
   (	"MERCHANT_ID" NUMBER(22,0), 
	"MERCHANT_PHONE" NVARCHAR2(100), 
	"MERCHANT_NAME" NVARCHAR2(250), 
	"MERCHANT_CODE" NVARCHAR2(250), 
	"PAPER_TYPE" NVARCHAR2(250), 
	"PAPER_NUMBER" NVARCHAR2(100), 
	"ISSUED_DATE" DATE, 
	"EXPIRED_DATE" DATE, 
	"ISSUED_PLACE" NVARCHAR2(250), 
	"GENDER" NVARCHAR2(20), 
	"BUSINESS_TYPE" NVARCHAR2(250), 
	"STATUS" NVARCHAR2(50), 
	"DEVELOPER_OBJECT" NVARCHAR2(50), 
	"MERCHANT_PHONE_DEVELOPER" NVARCHAR2(150), 
	"COUNTRY" NVARCHAR2(100), 
	"PROVINCE" NVARCHAR2(20), 
	"DISTRICT" NVARCHAR2(20), 
	"PRECINCT" NVARCHAR2(100), 
	"ADDRESS" NVARCHAR2(250), 
	"PARTY_ROLE_ID" NUMBER(12,0), 
	"ROLE_ID" NUMBER(12,0), 
	"TRANSACTION_ID" NUMBER(22,0), 
	"CREATED_DATE" DATE, 
	"CREATE_BY" NVARCHAR2(50), 
	"MODIFY_DATE" DATE, 
	"MODIFY_BY" NVARCHAR2(50), 
	"BUSINESS_SECTOR" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

