CREATE TABLE "EWALLET_V21"."MICROLET_MERCHANT" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"STATUS" NUMBER(1,0), 
	"CREATE_DATE" DATE, 
	"MSISDN" VARCHAR2(15), 
	"NOTE" VARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

