CREATE TABLE "EWALLET_V21"."MO" 
   (	"MO_ID" NUMBER(10,0), 
	"MSISDN" VARCHAR2(15) NOT NULL ENABLE, 
	"COMMAND" VARCHAR2(50) NOT NULL ENABLE, 
	"PARAM" VARCHAR2(1024), 
	"RECEIVE_TIME" DATE NOT NULL ENABLE, 
	"ACTION_TYPE" NUMBER(3,0), 
	"CHANNEL" VARCHAR2(15)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

