CREATE TABLE "EWALLET_V21"."MSSI_TEMP_PAY_COM" 
   (	"AMOUNT" NUMBER(30,5), 
	"ORG_AMOUNT" NUMBER(5,2), 
	"CUS_PHONE" VARCHAR2(15), 
	"DISTRICT" VARCHAR2(30), 
	"TRANSACTION_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"CUS_NAME" VARCHAR2(100), 
	"TRANS_ID" VARCHAR2(50), 
	"BIRTH_DAY" VARCHAR2(25), 
	"PAPER_NUMBER" VARCHAR2(50), 
	"STATUS" NUMBER, 
	"COM_AMOUNT" NUMBER, 
	"AGENT_PHONE" VARCHAR2(11), 
	"AGENT_ACC" VARCHAR2(6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

