CREATE TABLE "EWALLET_V21"."MSSI_BATCH_REQ" 
   (	"BATCH_ID" NUMBER(10,0), 
	"REQ_USER" VARCHAR2(100), 
	"REQ_DATE" DATE, 
	"MODIFIED_DATE" DATE, 
	"APPROVE_USER" VARCHAR2(20), 
	"STATUS" NUMBER(1,0) DEFAULT NULL, 
	"NUM_LIST" NUMBER(3,0) DEFAULT NULL, 
	"CONTRACT_URL" VARCHAR2(500), 
	"NOTE" VARCHAR2(1000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

