CREATE TABLE "EWALLET_V21"."MSSI_MAP_POST_DISTRICT" 
   (	"ID" NUMBER(5,0), 
	"DISTRICT" VARCHAR2(100), 
	"RUN_DATE" DATE, 
	"STATUS" NUMBER(1,0), 
	"HEALTH_POST" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

