CREATE TABLE "EWALLET_V21"."MSSI_CUS_INFOR_LOG" 
   (	"ID" NUMBER(10,0), 
	"ACTION_TYPE" VARCHAR2(50), 
	"TRANS_ID" VARCHAR2(50), 
	"CUS_PHONE" VARCHAR2(15), 
	"AMOUNT" NUMBER(5,2) NOT NULL ENABLE, 
	"STATUS" NUMBER(1,0) DEFAULT NULL, 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(20), 
	"NOTE" VARCHAR2(1000), 
	"AGENT_PHONE" VARCHAR2(20), 
	"STAGE" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

