CREATE TABLE "EWALLET_V21"."MT" 
   (	"MT_ID" NUMBER(10,0), 
	"MO_HIS_ID" NUMBER(10,0), 
	"MSISDN" VARCHAR2(15) NOT NULL ENABLE, 
	"MESSAGE" VARCHAR2(1024) NOT NULL ENABLE, 
	"RETRY_NUM" NUMBER(1,0) DEFAULT 0, 
	"CHANNEL" VARCHAR2(15), 
	"CTV" VARCHAR2(15), 
	"RECEIVE_TIME" DATE DEFAULT SYSDATE, 
	"SEND_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

