CREATE TABLE "EWALLET_V21"."MT_HIS" 
   (	"MT_HIS_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"MO_HIS_ID" NUMBER(10,0), 
	"MSISDN" VARCHAR2(15), 
	"MESSAGE" VARCHAR2(1024), 
	"RECEIVE_TIME" DATE, 
	"SENT_TIME" DATE, 
	"NODE_NAME" VARCHAR2(80), 
	"CLUSTER_NAME" VARCHAR2(80), 
	"STATUS" NUMBER(1,0), 
	"CHANNEL" VARCHAR2(15)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

