CREATE TABLE "EWALLET_V21"."NOC_METER_CONFIG" 
   (	"ID" NUMBER(10,0), 
	"SITE_CODE" VARCHAR2(15), 
	"DISTRICT" VARCHAR2(15), 
	"POWER_METER" VARCHAR2(50), 
	"STAFF_PHONE" VARCHAR2(15), 
	"STAFF_NAME" VARCHAR2(50), 
	"EMAIL" VARCHAR2(30), 
	"DATE_UPDATED" DATE, 
	"STATUS" NUMBER(1,0), 
	"URL_IMAGE" VARCHAR2(500), 
	"URL_DOC" VARCHAR2(500), 
	"DESCRIPTION" VARCHAR2(500), 
	"DATE_REPORT" DATE, 
	"DATE_UPLOAD_DOC" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

