CREATE TABLE "EWALLET_V21"."NOTIFICATION" 
   (	"ID" NUMBER(22,0), 
	"TYPE" NUMBER(2,0), 
	"ROLE_ID" NUMBER(2,0), 
	"CREATED_USER" VARCHAR2(200), 
	"CREATED_DATETIME" DATE, 
	"UPDATED_USER" VARCHAR2(200), 
	"UPDATED_DATETIME" DATE, 
	"STATUS" NUMBER(2,0), 
	"CONTENT_EN" VARCHAR2(1000), 
	"CONTENT_TL" VARCHAR2(1000), 
	"TITLE_EN" VARCHAR2(1000), 
	"TITLE_TL" VARCHAR2(1000), 
	"UPLOAD_DATETIME" DATE, 
	"BUTTON_TYPE" NUMBER(1,0), 
	"BUTTON_NAME_EN" VARCHAR2(500), 
	"BUTTON_NAME_TL" VARCHAR2(500), 
	"LINK_TO" VARCHAR2(500), 
	"IMAGE_BANNER" VARCHAR2(500), 
	"SHOW_AT_HOME" NUMBER(1,0), 
	"FROM_DATE" DATE, 
	"TO_DATE" DATE, 
	"RETRY" NUMBER(20,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

