CREATE TABLE "EWALLET_V21"."OAUTH_CLIENT_TOKEN" 
   (	"TOKEN_ID" VARCHAR2(255), 
	"TOKEN" BLOB, 
	"AUTHENTICATION_ID" VARCHAR2(255), 
	"USER_NAME" VARCHAR2(255), 
	"CLIENT_ID" VARCHAR2(255)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" 
 LOB ("TOKEN") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

