CREATE TABLE "EWALLET_V21"."OTP2" 
   (	"OTP_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"ACCOUNT_ID" VARCHAR2(12), 
	"LOCK_TIME" DATE, 
	"STATUS" NUMBER(2,0) DEFAULT 1, 
	"CREATED_DATE" DATE, 
	"MSISDN" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

