CREATE TABLE "EWALLET_V21"."OTP_20190502" 
   (	"OTP_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"ACCOUNT_ID" VARCHAR2(12), 
	"LOCK_TIME" DATE, 
	"STATUS" NUMBER(2,0), 
	"CREATED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

