CREATE TABLE "EWALLET_V21"."OTP_VALUE_20190502" 
   (	"OTP_VALUE_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"ACCOUNT_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"VALUE" VARCHAR2(50), 
	"CREATED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

