CREATE TABLE "EWALLET_V21"."PACKAGE_DISCOUNT_CONFIG" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PCK_ID" NUMBER NOT NULL ENABLE, 
	"DISCOUNT" NUMBER, 
	"DISCOUNT_OTHER" NUMBER, 
	"FROM_DATE_DIS" DATE, 
	"TO_DATE_DIS" DATE, 
	"DISCOUNT_SPECIAL" NUMBER, 
	"DISCOUNT_SPECIAL_OTHER" NUMBER, 
	"FROM_DATE_DIS_SPECIAL" DATE, 
	"TO_DATE_DIS_SPECIAL" DATE, 
	"STATUS" NUMBER DEFAULT 1 NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

