CREATE TABLE "EWALLET_V21"."PACKAGE_BONUS_CONFIG" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"PCK_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"STATUS" NUMBER(1,0), 
	"VALUE" NUMBER(10,2), 
	"EXIRE_NUM" NUMBER(3,0), 
	"ACC_ID" VARCHAR2(5), 
	"ACC_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	"CREATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

