CREATE TABLE "EWALLET_V21"."PAPER_TYPE" 
   (	"PAPER_TYPE" VARCHAR2(4) NOT NULL ENABLE, 
	"PAPER_NAME" VARCHAR2(30 CHAR), 
	"LOCALE_KEY" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

