CREATE TABLE "EWALLET_V21"."PARTY_DEVICES" 
   (	"DEVICES_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"PARTY_ROLE_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"OS_TYPE" NUMBER(8,0), 
	"OS_VERSION" VARCHAR2(15), 
	"GUID" VARCHAR2(50) NOT NULL ENABLE, 
	"MODEL_NAME" VARCHAR2(50), 
	"LAST_USED" DATE, 
	 CONSTRAINT "PK_PDS" PRIMARY KEY ("DEVICES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

