CREATE TABLE "EWALLET_V21"."PARTY_CONTACT" 
   (	"CONTACT_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"CONTACT_MEDIUM_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"CONTACT_NAME" VARCHAR2(50), 
	"PARTY_ROLE_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"STATUS" NUMBER(1,0), 
	 CONSTRAINT "PK_PCT" PRIMARY KEY ("CONTACT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

