CREATE TABLE "EWALLET_V21"."PARTNER_CONFIG" 
   (	"PARTNER_CONFIG_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"USER_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(1000), 
	"PUBLIC_KEY" VARCHAR2(2000), 
	"PRIVATE_KEY" VARCHAR2(2000), 
	"STATUS" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"PATH_FILE_EXPORT" VARCHAR2(1000), 
	"MAC_KEY" VARCHAR2(1000), 
	"DESCRIPTION" VARCHAR2(1000), 
	"PARTNER_CODE" VARCHAR2(20), 
	"PARTNER_NAME" VARCHAR2(100), 
	"CLIENT_ID" VARCHAR2(100), 
	"PRIORITY" NUMBER(2,0), 
	"CURRENT_BALANCE" NUMBER(30,5), 
	"AVAILABLE_BALANCE" NUMBER(30,5), 
	"DATE_CREATED" DATE, 
	"CREATED_BY" VARCHAR2(20), 
	"DATE_MODIFIED" DATE, 
	"MODIFIED_BY" VARCHAR2(20), 
	"TERMINAL_ID" VARCHAR2(50), 
	"IP_ADDRESS" VARCHAR2(50), 
	"OPERATOR_NAME" VARCHAR2(50), 
	"LAST_LOGIN_TIME" DATE, 
	"HASH_KEY" VARCHAR2(250), 
	"ROLE_NAME" VARCHAR2(100), 
	 CONSTRAINT "PARNER_CONFIG_PK" PRIMARY KEY ("PARTNER_CONFIG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

