CREATE TABLE "EWALLET_V21"."PARTY_PAPER" 
   (	"PAPER_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"PAPER_NUMBER" VARCHAR2(25) NOT NULL ENABLE, 
	"PAPER_TYPE" VARCHAR2(4), 
	"STATUS" NUMBER(5,0), 
	"ISSUED_DATE" DATE, 
	"EXPIRED_DATE" DATE, 
	"ISSUED_PLACE" VARCHAR2(50), 
	"ISSUED_COUNTRY" VARCHAR2(3), 
	"PAPER_IMAGE" VARCHAR2(256), 
	"PARTY_ID" NUMBER(12,0), 
	"CREATED_DATE" TIMESTAMP (7), 
	"MODIFY_BY" VARCHAR2(50), 
	"MODIFY_DATE" DATE, 
	 CONSTRAINT "PK_PPR" PRIMARY KEY ("PAPER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

