CREATE TABLE "EWALLET_V21"."PARTNER_SERVICES" 
   (	"SERVICE_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATED_DATE" DATE, 
	"SERVICE_CODE" VARCHAR2(255 CHAR), 
	"SERVICE_NAME" VARCHAR2(255 CHAR), 
	"UPDATED_AT" DATE, 
	"PARTNER_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	 PRIMARY KEY ("SERVICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

