CREATE TABLE "EWALLET_V21"."PARTY" 
   (	"PARTY_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"BIRTHDAY" DATE, 
	"MARITAL_STATUS" NUMBER(8,0), 
	"GENDER" NVARCHAR2(20), 
	"NATIONALITY" VARCHAR2(3), 
	"PREFERRED_LANGUAGE" VARCHAR2(5), 
	"DESCRIPTION" VARCHAR2(200), 
	"ARISTOCRATIC_TITLE" VARCHAR2(50), 
	"GENERATION" VARCHAR2(50), 
	"GIVEN_NAME" VARCHAR2(100), 
	"PREFERRED_GIVEN_NAME" VARCHAR2(50), 
	"MIDDLE_NAME" VARCHAR2(50), 
	"FAMILY_NAME_PREFIX" VARCHAR2(50), 
	"FAMILY_NAME" VARCHAR2(50), 
	"FAMILY_GENERATION" VARCHAR2(50), 
	"QUALIFICATORS" VARCHAR2(50), 
	"DISABILITY" NUMBER(8,0), 
	"AVATAR" BLOB, 
	"IS_ORGANIZATION" NUMBER(1,0), 
	"TRADING_NAME" VARCHAR2(100), 
	"LOGO" BLOB, 
	"TIN" VARCHAR2(20), 
	"ORGANIZATION_TYPE" NUMBER(8,0), 
	"VALIDATATION_STATUS" NUMBER(8,0), 
	"AREA_CODE" VARCHAR2(50), 
	"ADDRESS" VARCHAR2(500), 
	"CREATED_DATE" TIMESTAMP (7), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(50), 
	"MODIFY_BY" VARCHAR2(50), 
	"FIRST_NAME" VARCHAR2(50), 
	"LAST_NAME" VARCHAR2(50), 
	"LATITUDE" NUMBER, 
	"LONGITUDE" NUMBER, 
	"TELEX" VARCHAR2(20), 
	"FAX" VARCHAR2(20), 
	"EMAIL" VARCHAR2(150), 
	"USE_BANK_ACC" NUMBER(2,0), 
	 CONSTRAINT "PK_PY" PRIMARY KEY ("PARTY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 2 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("AVATAR") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("LOGO") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

