CREATE TABLE "EWALLET_V21"."PARTNER_LOG" 
   (	"PARTNER_LOG_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"TRANSACTION_ID" NUMBER(22,0), 
	"ACTION_ID" NUMBER(22,0), 
	"REQUEST_ID" NUMBER, 
	"UNIQUE_ID" RAW(16), 
	"PARTNER_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30), 
	"USER_NAME" VARCHAR2(30), 
	"ACTION" VARCHAR2(50), 
	"REQUEST_DATE" DATE, 
	"RESPONSE_DATE" DATE, 
	"HEADERS" VARCHAR2(500), 
	"PARAMS" VARCHAR2(500), 
	"REQUEST_CONTENT" CLOB, 
	"RESPONSE_CONTENT" CLOB, 
	"RESPONSE_CODE" VARCHAR2(30), 
	"RESPONSE_DESC" VARCHAR2(200), 
	"ALERT_ID" NUMBER, 
	"ERROR_CODE" NUMBER, 
	"ERROR_DESC" VARCHAR2(200), 
	 CONSTRAINT "PARTNER_LOG_PK" PRIMARY KEY ("PARTNER_LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 4 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("REQUEST_CONTENT") STORE AS SECUREFILE (
  ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("RESPONSE_CONTENT") STORE AS SECUREFILE (
  ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
  PARTITION BY RANGE ("REQUEST_DATE") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) 
 (PARTITION "PARTNER_LOG_P1"  VALUES LESS THAN (TO_DATE(' 2020-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("REQUEST_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("RESPONSE_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ) ;

