CREATE TABLE "EWALLET_V21"."PARTNER_LOG_20200303" 
   (	"PARTNER_LOG_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"PARTNER_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(30), 
	"USER_NAME" VARCHAR2(30), 
	"ACTION" VARCHAR2(50), 
	"REQUEST_ID" NUMBER, 
	"REQUEST_DATE" DATE, 
	"RESPONSE_DATE" DATE, 
	"REQUEST_CONTENT" CLOB, 
	"RESPONSE_CONTENT" CLOB, 
	"ERROR_CODE" NUMBER, 
	"ERROR_DESC" VARCHAR2(200), 
	"ALERT_ID" NUMBER, 
	"RESPONSE_CODE" VARCHAR2(30), 
	"RESPONSE_DESC" VARCHAR2(200)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("REQUEST_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("RESPONSE_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

