CREATE TABLE "EWALLET_V21"."PARTY_INFO" 
   (	"PARTY_ID" NUMBER(22,0), 
	"MSISDN" VARCHAR2(20) NOT NULL ENABLE, 
	"LANGUAGE" VARCHAR2(5) NOT NULL ENABLE, 
	"PARTITION_KEY" VARCHAR2(2) NOT NULL ENABLE, 
	"UPDATED_DATE" DATE, 
	 CONSTRAINT "PARTY_INFO_PK" PRIMARY KEY ("MSISDN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

