CREATE TABLE "EWALLET_V21"."PHUONGBV4_BONUS" 
   (	"TRANSACTION_ID" NUMBER(22,0), 
	"REQUEST_NO" VARCHAR2(50), 
	"DATE_CREATED" DATE, 
	"ISDN" VARCHAR2(20), 
	"AMOUNT" NUMBER(30,5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

