CREATE TABLE "EWALLET_V21"."PROCESS_MAPPING" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PROCESS_CODE" VARCHAR2(6) NOT NULL ENABLE, 
	"STEP_ACCOUNTING" NUMBER(2,0) NOT NULL ENABLE, 
	"BUSINESS_STATE" NUMBER(2,0) NOT NULL ENABLE, 
	"FROM_ACC" VARCHAR2(50), 
	"FROM_ACC_TYPE" NUMBER(2,0), 
	"TO_ACC" VARCHAR2(50), 
	"TO_ACC_TYPE" NUMBER(2,0), 
	"EXPRESSION" VARCHAR2(50) NOT NULL ENABLE, 
	"EXP_TYPE" NUMBER(2,0) NOT NULL ENABLE, 
	"CURRENCY_CODE" VARCHAR2(5) NOT NULL ENABLE, 
	"RUN_ORDER" NUMBER(2,0) NOT NULL ENABLE, 
	"IS_PENDING" NUMBER(2,0) NOT NULL ENABLE, 
	"STATE_EXEC_PENDING" NUMBER(8,0), 
	"TRANS_STATE_ID" NUMBER(8,0), 
	"PARTNER_CODE" VARCHAR2(100), 
	"SERVICE_CODE" VARCHAR2(100), 
	"TRANS_TYPE_ID" NUMBER(8,0), 
	"ACCOUNTING_TYPE_ID" NUMBER, 
	 CONSTRAINT "PROCESS_MAPPING_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 2 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

