CREATE TABLE "EWALLET_V21"."PROMOTION_HISTORY" 
   (	"TRANSACTION_ID" NUMBER, 
	"PROMOTION_ID" NUMBER, 
	"ACCOUNT_ID" NUMBER, 
	"AMOUNT" NUMBER, 
	"CREATE_DATE" DATE, 
	"STATUS" NUMBER, 
	"UPDATE_DATE" DATE, 
	"RESPONSE" VARCHAR2(1000), 
	"NEXT_RETRY" DATE, 
	"PROMOTION_TRANS_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

