CREATE TABLE "EWALLET_V21"."PROMOTION_FREE_PACKAGE_LOG" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"STATUS" NUMBER(1,0), 
	"CREATE_DATE" DATE, 
	"PACKAGE_CODE" VARCHAR2(50), 
	"MSISDN" VARCHAR2(30), 
	"MONEY" NUMBER(10,2), 
	"TRANSACTION_ID" VARCHAR2(50), 
	"DESCRIPTION" VARCHAR2(300), 
	"BONUS_TYPE" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

