CREATE TABLE "EWALLET_V21"."PROMOTION_11_PACKAGE_BD" 
   (	"DAY_BONUS" NUMBER(3,0), 
	"HOUR_BONUS" NUMBER(3,0), 
	"CREATE_DATE" DATE, 
	"UPDATE_DATE" DATE, 
	"PACKAGE_CODE" VARCHAR2(20), 
	"MSISDN" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

