CREATE TABLE "EWALLET_V21"."PROMOTION" 
   (	"PROMOTION_ID" NUMBER NOT NULL ENABLE, 
	"CODE" VARCHAR2(10), 
	"AMOUNT" NUMBER DEFAULT 0.5, 
	"STATUS" NUMBER, 
	"CREATE_DATE" DATE, 
	"CREATE_BY" VARCHAR2(30), 
	"UPDATE_DATE" DATE, 
	"UPDATE_BY" VARCHAR2(30), 
	"TYPE" NUMBER, 
	"VALID_FROM" DATE, 
	"VALID_TO" DATE, 
	"ROLE" NUMBER, 
	"DESCRIPTION" VARCHAR2(255), 
	 PRIMARY KEY ("PROMOTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

