CREATE TABLE "EWALLET_V21"."PROMOTION_DJ_PACKAGE" 
   (	"ID" NUMBER(5,0), 
	"CREATE_DATE" DATE, 
	"UPDATE_DATE" DATE, 
	"STATUS" NUMBER(1,0), 
	"MSISDN" VARCHAR2(20), 
	"NOTE" VARCHAR2(500), 
	"DAY_SEND_SMS" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

