CREATE TABLE "EWALLET_V21"."PROMOTION_FREE_PACKAGE_LOG_BK" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"STATUS" NUMBER(1,0), 
	"CREATE_DATE" DATE, 
	"PACKAGE_CODE" VARCHAR2(20), 
	"MSISDN" VARCHAR2(20), 
	"MONEY" NUMBER(5,2), 
	"TRANSACTION_ID" VARCHAR2(30), 
	"DESCRIPTION" VARCHAR2(200), 
	"BONUS_TYPE" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

