CREATE TABLE "EWALLET_V21"."PUSH_POS_HISTORY" 
   (	"PUSH_ID" NUMBER(22,0), 
	"AGENT_ID" NUMBER(22,0), 
	"REQUEST_ID" NUMBER(22,0), 
	"STATUS" NUMBER(2,0), 
	"CREATED_DATETIME" DATE, 
	"UPDATED_DATETIME" DATE, 
	"REJECT_REASON" NUMBER(10,0), 
	"EXPIRED_DATETIME" DATE, 
	"PEND_ACCEPT_DURATION" NUMBER(10,0), 
	"PEND_BUY_DURATION" NUMBER(10,0), 
	"MIN_AMOUNT" NUMBER(10,0), 
	"MAX_AMOUNT" NUMBER(10,0), 
	"POS_TYPE" VARCHAR2(20), 
	"REASON_CONTENT" VARCHAR2(500), 
	"NO_OF_EXPIRED_TIMES" NUMBER(*,0), 
	"EXPIRED_WAITING" DATE, 
	"EXPIRED_ACCEPT" DATE, 
	"NO_OF_REJECT_TIMES" NUMBER(22,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

