CREATE TABLE "EWALLET_V21"."RECONCILE_REPORT_LOTTO" 
   (	"ID" NUMBER, 
	"TRANSACTION_ID" NUMBER, 
	"TRANSACTION_TYPE" VARCHAR2(20), 
	"DISCOUNT_RATE" NUMBER, 
	"CUSTOMER_PHONE" VARCHAR2(200), 
	"DISCOUNT" NUMBER, 
	"AMOUNT" NUMBER, 
	"TOTAL_PAY" NUMBER, 
	"ORDER_ID" VARCHAR2(200), 
	"PRODUCT_CODE" VARCHAR2(200), 
	"LOTTO_CODE" VARCHAR2(200), 
	"NUMBER_CODE" VARCHAR2(200), 
	"TRANS_DATE" DATE, 
	"STATUS" VARCHAR2(20), 
	"DETAIL" VARCHAR2(500), 
	"MOBILE_NUMBER_PARTNER" VARCHAR2(20), 
	"AMOUNT_PARTNER" NUMBER, 
	"ORDER_ID_PARTNER" VARCHAR2(200), 
	"PRODUCT_CODE_PARTNER" VARCHAR2(200), 
	"LOTTO_CODE_PARTNER" VARCHAR2(200), 
	"NUMBER_CODE_PARTNER" VARCHAR2(200), 
	"TRANS_DATE_PARTNER" DATE, 
	"STATUS_PARTNER" VARCHAR2(20), 
	"REASON_REVERT" VARCHAR2(200), 
	"CARRIED_PHONE" VARCHAR2(20), 
	"STATUS_RECONCILE" VARCHAR2(20), 
	"SCAN_COUNT" NUMBER, 
	"TRANS_ID_REVERT" NUMBER, 
	"SCAN_DATE" DATE, 
	"ERROR_DESCRIPTION" VARCHAR2(200), 
	"CARRIED_ACC_ID" NUMBER, 
	"TRANS_STATE_ID" NUMBER(22,0), 
	"STATUS_WIN" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS  LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
  PARTITION BY RANGE ("TRANS_DATE") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) 
 (PARTITION "LOG_DATA_P1"  VALUES LESS THAN (TO_DATE(' 2017-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" )  ENABLE ROW MOVEMENT ;

