CREATE TABLE "EWALLET_V21"."REFERRAL_HISTORY" 
   (	"ID" NUMBER, 
	"TRANSACTION_ID" NUMBER, 
	"ACCOUNT_ID" NUMBER, 
	"AMOUNT" NUMBER, 
	"CREATE_DATE" DATE, 
	"STATUS" NUMBER, 
	"UPDATE_DATE" DATE, 
	"RESPONSE" VARCHAR2(1000), 
	"NEXT_RETRY" DATE, 
	"PROMOTION_TRANS_ID" NUMBER, 
	"TYPE" NUMBER, 
	"REFERRAL_ACC_ID" NUMBER, 
	"NUM_DAY" NUMBER(10,0), 
	"MESSAGE_EN" VARCHAR2(1000), 
	"MESSAGE_TL" VARCHAR2(1000), 
	"REWARD_BUSINESS" NUMBER, 
	 CONSTRAINT "REFERRAL_HIS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

