CREATE TABLE "EWALLET_V21"."REGISTER_ACTION_REPORT" 
   (	"PARTY_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"ROLE_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"PARTY_ROLE_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"ACCOUNT_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(50), 
	"MSISDN" VARCHAR2(20) NOT NULL ENABLE, 
	"SIM_IMSI" VARCHAR2(50), 
	"ACTION_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"CARRIED_PARTY" NUMBER(12,0), 
	"REGISTER_TYPE" NUMBER(5,0) NOT NULL ENABLE, 
	"REASON_ID" NUMBER(5,0), 
	"DATE_CREATED" DATE NOT NULL ENABLE, 
	"ACTION_NODE_ID" NUMBER(12,0), 
	"CARRIED_ACCOUNT" VARCHAR2(50), 
	"CARRIED_CODE" VARCHAR2(50), 
	"CARRIED_NAME" VARCHAR2(100), 
	"PROCESS_CODE" VARCHAR2(20), 
	"TRANSACTION_ID" NUMBER(12,0), 
	"APPROVED_USER" VARCHAR2(50), 
	"APPROVED_DATE" DATE, 
	"REJECT_REASON" VARCHAR2(500), 
	"ACTION_STATE_ID" NUMBER, 
	"REJECT_REASON_TYPE" NUMBER(5,0), 
	"REJECT_REASON_DETAIL" NUMBER(5,0), 
	"USER_TYPE" VARCHAR2(200), 
	"USER_CENTER" VARCHAR2(200), 
	"CARRIED_PHONE" VARCHAR2(200), 
	"PARTNER_CODE" VARCHAR2(200), 
	"USER_NAME_PARTNER" VARCHAR2(200), 
	"IS_PAY_COMMISSION" VARCHAR2(20), 
	"USER_CODE" VARCHAR2(100), 
	"BCCS_AI" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

