CREATE TABLE "EWALLET_V21"."REPORT_KPI_NETBI" 
   (	"ID" NUMBER(10,0), 
	"COUNTRY" VARCHAR2(30), 
	"AREA_NAME" VARCHAR2(30), 
	"PROVINCE_CODE" VARCHAR2(50), 
	"PROVINCE_NAME" VARCHAR2(50), 
	"KPI_VALUE" NUMBER(5,2), 
	"KPI_CODE" VARCHAR2(50), 
	"LOCATION_LEVEL" VARCHAR2(30), 
	"TIME_TYPE" VARCHAR2(30), 
	"TIME_VALUE" VARCHAR2(30), 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

