CREATE TABLE "EWALLET_V21"."REQUEST_POS" 
   (	"REQUEST_ID" NUMBER(22,0), 
	"METER_NUMBER" VARCHAR2(20), 
	"AMOUNT" NUMBER(22,6), 
	"POS_COMMISION" NUMBER(22,6), 
	"AGENT_COMMISION" NUMBER(22,6), 
	"FEE" NUMBER(22,6), 
	"CUSTOMER_PHONE" VARCHAR2(20), 
	"CARRIED_CODE" VARCHAR2(50), 
	"CARRIED_PHONE" VARCHAR2(20), 
	"CARRIED_ROLE" NUMBER(4,0), 
	"REQUEST_TYPE" NUMBER(2,0), 
	"STATUS" NUMBER(2,0), 
	"CREATED_DATETIME" DATE, 
	"UPDATED_DATETIME" DATE, 
	"APPROVED_USER_ID" NUMBER(12,0), 
	"TOKEN" VARCHAR2(20), 
	"REJECTED_TIME" NUMBER(4,0), 
	"FAIL_REASON" VARCHAR2(500), 
	"TRANSACTION_ID" NUMBER(22,0), 
	"CARRIED_ID" NUMBER(22,0), 
	"ACTION_NODE_ID" NUMBER(8,0), 
	"ACTION_ID" NUMBER(22,0), 
	"PENDING_UPLOAD_FILE" VARCHAR2(30), 
	"TOTAL_KWH" VARCHAR2(30), 
	"ACTION_ID_DETECT" NUMBER(22,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

