CREATE TABLE "EWALLET_V21"."REQUEST_POS_TEMP" 
   (	"REQUEST_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"METER_NUMBER" VARCHAR2(20), 
	"AMOUNT" NUMBER(22,6), 
	"POS_COMMISION" NUMBER(22,6), 
	"AGENT_COMMISION" NUMBER(22,6), 
	"FEE" NUMBER(22,6), 
	"CUSTOMER_PHONE" VARCHAR2(20), 
	"CARRIED_PHONE" VARCHAR2(20), 
	"CREATED_DATETIME" DATE, 
	"UPDATED_DATETIME" DATE, 
	"FAIL_REASON" VARCHAR2(500), 
	"TOKEN" VARCHAR2(20), 
	"TRANSACTION_ID" NUMBER(22,0), 
	"STATUS" NUMBER, 
	"STATUS_SEND" NUMBER, 
	"SEND_TIME" DATE, 
	"BOT_TYPE" NUMBER(1,0), 
	"TOTAL_KWH" VARCHAR2(30), 
	"IMAGE_URL" VARCHAR2(1000), 
	 CONSTRAINT "REQUEST_POS_TEMP_PK" PRIMARY KEY ("REQUEST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

