CREATE TABLE "EWALLET_V21"."RP_COMMISSION_DAILY" 
   (	"FACT_DATE" DATE, 
	"PROCESS_CODE" VARCHAR2(6 CHAR), 
	"DEBIT" NUMBER(30,6), 
	"PAYMENT_STATUS" NUMBER(2,0), 
	"ACTION_TYPE_NAME" VARCHAR2(100 CHAR), 
	"DATE_CREATED" DATE DEFAULT sysdate
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS  LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
  PARTITION BY RANGE ("DATE_CREATED") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) 
 (PARTITION "LOG_DATA_P1"  VALUES LESS THAN (TO_DATE(' 2017-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ) ;

