CREATE TABLE "EWALLET_V21"."RP_DAILY_AUDIT" 
   (	"RP_DAILY_AUDIT_ID" NUMBER NOT NULL ENABLE, 
	"CODE" VARCHAR2(30), 
	"NAME" VARCHAR2(100), 
	"BALANCE" NUMBER(18,6), 
	"CREDIT" NUMBER(18,6), 
	"DEBIT" NUMBER(18,6), 
	"ACCOUNT_ID" NUMBER(20,0), 
	"DATE_CREATED" DATE, 
	"DATE_MODIFIED" DATE, 
	"DATE_AUDIT" DATE, 
	"ROLE_ID" NUMBER, 
	"ACCOUNT_TYPE_ID" NUMBER DEFAULT 1, 
	"CURRENCY_ID" NUMBER DEFAULT 5, 
	"CURRENCY_CODE" VARCHAR2(10), 
	 CONSTRAINT "RP_DAILY_AUDIT_PK" PRIMARY KEY ("RP_DAILY_AUDIT_ID")
  USING INDEX PCTFREE 10 INITRANS 4 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS  LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
  PARTITION BY RANGE ("DATE_CREATED") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) 
 (PARTITION "LOG_DATA_P1"  VALUES LESS THAN (TO_DATE(' 2017-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ) ;

