CREATE TABLE "EWALLET_V21"."RP_EXECUTIVE_BUSINESS_CONFIG" 
   (	"ID" NUMBER DEFAULT ewallet_dev."ISEQ$$_107400".nextval NOT NULL ENABLE, 
	"CATAGORY_ID" NUMBER, 
	"FROM_VALUE" NUMBER, 
	"TO_VALUE" NUMBER, 
	"VALUE" NUMBER, 
	"VALUE_TYPE" NUMBER, 
	"MIN_VALUE" NUMBER, 
	"MAX_VALUE" NUMBER, 
	"VALID_FROM" DATE, 
	"VALID_TO" DATE, 
	"STATUS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

