CREATE TABLE "EWALLET_V21"."RP_EXECUTIVE_BUSINESS_ITEM" 
   (	"CATAGORY_CODE" NUMBER, 
	"NAME" VARCHAR2(100), 
	"TRANS_TYPE_ID" NUMBER, 
	"PROCESS_CODE" VARCHAR2(6), 
	"CONDITION" VARCHAR2(200), 
	"ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "REPORT_EXECUTIVE_BUSINESS__PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

