CREATE TABLE "EWALLET_V21"."RP_KPI" 
   (	"ID" NUMBER, 
	"ORDER_NO" NUMBER NOT NULL ENABLE, 
	"LOG_DATE" DATE NOT NULL ENABLE, 
	"DATE_CREATED" DATE NOT NULL ENABLE, 
	"KPI" VARCHAR2(50) NOT NULL ENABLE, 
	"KPI_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"PARAM_NUM_1" NUMBER, 
	"PARAM_STR_1" VARCHAR2(50), 
	"PARAM_DATE_1" DATE, 
	"TRANS_TOTAL" NUMBER NOT NULL ENABLE, 
	"TRANS_SATISFY" NUMBER NOT NULL ENABLE, 
	"TARGET" NUMBER NOT NULL ENABLE, 
	"RESULT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

