CREATE TABLE "EWALLET_V21"."RP_SUB_DEV_DAILY" 
   (	"RP_SUB_DEV_DAILY_ID" VARCHAR2(20), 
	"ROLE_ID" NUMBER, 
	"ACCOUNT_ID" NUMBER, 
	"ACTIVE_TIME" DATE, 
	"LAST_TRANS_TIME" DATE, 
	"BALANCE" NUMBER(18,0), 
	"ACCOUNT_STATE_ID" NUMBER, 
	"DATE_CREATED" DATE, 
	"DATE_MODIFIED" DATE, 
	"DATE_AUDIT" DATE, 
	"AREA_CODE_ID" NUMBER, 
	"AREA_CODE" VARCHAR2(20), 
	"LAST_CHANGE_BALANCE_TIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

