CREATE TABLE "EWALLET_V21"."RP_TRANS_DAILY" 
   (	"ID" NUMBER, 
	"LOG_DATE" DATE NOT NULL ENABLE, 
	"DATE_CREATED" DATE NOT NULL ENABLE, 
	"ACCOUNT_ID" NUMBER, 
	"ROLE_ID" NUMBER(2,0), 
	"CODE" VARCHAR2(20), 
	"PHONE" VARCHAR2(20), 
	"NAME" VARCHAR2(100), 
	"AGENT_ACC_ID" NUMBER, 
	"AGENT_CODE" VARCHAR2(10), 
	"AGENT_PHONE" VARCHAR2(20), 
	"AGENT_NAME" VARCHAR2(100), 
	"AREA_CODE" VARCHAR2(10), 
	"AREA_NAME" VARCHAR2(100), 
	"COUNTRY" VARCHAR2(20), 
	"COUNTRY_NAME" VARCHAR2(100), 
	"PROVINCE" VARCHAR2(20), 
	"PROVINCE_NAME" VARCHAR2(100), 
	"DISTRICT" VARCHAR2(20), 
	"DISTRICT_NAME" VARCHAR2(100), 
	"SUB_DISTRICT" VARCHAR2(20), 
	"SUB_DISTRICT_NAME" VARCHAR2(100), 
	"WARD" VARCHAR2(20), 
	"WARD_NAME" VARCHAR2(100), 
	"ADDRESS" VARCHAR2(200), 
	"TRANS_TYPE" NUMBER(3,0), 
	"PROCESS_CODE" VARCHAR2(15) NOT NULL ENABLE, 
	"TO_ACC_ID" NUMBER, 
	"TO_ROLE_ID" NUMBER, 
	"TO_PHONE" VARCHAR2(20), 
	"TO_NAME" VARCHAR2(100), 
	"TO_AREA" VARCHAR2(10), 
	"ACTION_STATE" VARCHAR2(2), 
	"TRANS_STATE" VARCHAR2(2), 
	"TRANS_COUNT" NUMBER NOT NULL ENABLE, 
	"AMOUNT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
  PARTITION BY RANGE ("LOG_DATE") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) 
 (PARTITION "DATA_P1"  VALUES LESS THAN (TO_DATE(' 2019-12-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ) ;

