CREATE TABLE "EWALLET_V21"."RPT_LOTTERY_REWARD" 
   (	"ID" NUMBER(22,0), 
	"TRANSACTION_ID" NUMBER(22,0), 
	"CUSTOMER_PHONE" VARCHAR2(20), 
	"AMOUNT" NUMBER(38,5), 
	"FEE" NUMBER(38,5), 
	"ORDER_ID" VARCHAR2(50), 
	"TRANS_DATE" DATE, 
	"TRANS_STATUS" VARCHAR2(20), 
	"CLAIM_STATUS_PARTNER" VARCHAR2(20), 
	"REASON" VARCHAR2(500), 
	"CREATED_DATE" DATE, 
	"UPDATED_DATE" DATE, 
	"ORDER_ID_RECEIVED" NUMBER(1,0), 
	 CONSTRAINT "PK_RPT_LOTTERY_REWARD" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
  PARTITION BY RANGE ("CREATED_DATE") INTERVAL (INTERVAL '1' MONTH) 
 (PARTITION "P1"  VALUES LESS THAN (TO_DATE(' 2025-02-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ) ;

