CREATE TABLE "EWALLET_V21"."RPT_UMONEY_SUM_BI" 
   (	"ID" VARCHAR2(20), 
	"SUM_DATE" DATE, 
	"ITEM_ID" VARCHAR2(10), 
	"VALUE_DAY" NUMBER, 
	"VALUE_MON" NUMBER, 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"DESCRIPTION" VARCHAR2(100), 
	"SYN_STATUS" VARCHAR2(1) DEFAULT '0', 
	"SYN_DATE" DATE, 
	"SYN_DES" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

