CREATE TABLE "EWALLET_V21"."RULE_BASE" 
   (	"RULE_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"RULE_NAME" VARCHAR2(50), 
	"DATE_CREATED" DATE, 
	"WHO_CREATED" VARCHAR2(50), 
	"VARIABLE" VARCHAR2(50), 
	"VARIABLE_TYPE" NUMBER(5,0), 
	"ORDER_RULE" NUMBER(2,0), 
	"COLUMN_NAME" VARCHAR2(50), 
	"CONDITION" VARCHAR2(2000), 
	"TRANSACTION_TYPE" NUMBER(2,0), 
	"ERROR_CODE" NUMBER(5,0), 
	"DESCRIPTION" VARCHAR2(500), 
	 CONSTRAINT "PK_RBE" PRIMARY KEY ("RULE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 2 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

