CREATE TABLE "EWALLET_V21"."RULE_ALERT_ACTION" 
   (	"RULE_ALERT_ID" NUMBER NOT NULL ENABLE, 
	"ACTION_TYPE" NUMBER, 
	"ACTION" VARCHAR2(20), 
	"RECIPIENT" VARCHAR2(50), 
	"CONTENT_KEY" VARCHAR2(50), 
	"STATUS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

