CREATE TABLE "EWALLET_V21"."RULE_SET" 
   (	"RULE_SET_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(50), 
	"STATUS" NUMBER(5,0), 
	"WHO_CREATED" VARCHAR2(30), 
	"DATE_CREATED" DATE, 
	"VERSION" VARCHAR2(10), 
	"CREATED_BY" VARCHAR2(50), 
	"MODIFIED_BY" VARCHAR2(50), 
	"LAST_MODIFIED" DATE, 
	"CURRENCY_ID" NUMBER(8,0) DEFAULT 5, 
	"CURRENCY_CODE" VARCHAR2(5), 
	 CONSTRAINT "PK_RST" PRIMARY KEY ("RULE_SET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 2 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

