CREATE TABLE "EWALLET_V21"."RULE_ALERT" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CODE" VARCHAR2(30), 
	"DESCRIPTION" VARCHAR2(100), 
	"STATUS" NUMBER, 
	"VALID_FROM" DATE, 
	"VALID_TO" DATE, 
	"FREQUENCY" NUMBER, 
	"FREQUENCY_TYPE" NUMBER, 
	"CREATED_BY" VARCHAR2(50), 
	"DATE_CREATED" DATE, 
	"MODIFIED_BY" VARCHAR2(50), 
	"DATE_MODIFIED" DATE, 
	"SCRIPT_CONDITION" VARCHAR2(4000), 
	"SCRIPT_MSG_PARAM" VARCHAR2(4000), 
	"LAST_RUN" DATE, 
	"START_WHEN" NUMBER, 
	"END_WHEN" NUMBER, 
	 CONSTRAINT "RULE_ALERT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

