CREATE TABLE "EWALLET_V21"."RULE_APPLIED_DF_20190916" 
   (	"POLICY_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"TIER" NUMBER(8,0), 
	"RULE_SET_ID" NUMBER(8,0), 
	"ACCOUNT_TYPE_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"STATUS" NUMBER(5,0), 
	"ROLE_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"VALID_FROM" DATE, 
	"VALID_TO" DATE, 
	"PRIORITY" NUMBER(3,0), 
	"CREATED_BY" VARCHAR2(50), 
	"MODIFIED_BY" VARCHAR2(50), 
	"CREATED_TIME" DATE, 
	"LAST_MODIFIED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

