CREATE TABLE "EWALLET_V21"."RULE_ALERT_CONDITION" 
   (	"CONDITION_ID" NUMBER NOT NULL ENABLE, 
	"RULE_ALERT_ID" NUMBER NOT NULL ENABLE, 
	"SQL_PART" VARCHAR2(20), 
	"SQL_EXPRESSION" VARCHAR2(50), 
	"SQL_OPERATOR" VARCHAR2(20), 
	"PARAM" VARCHAR2(50), 
	"OPERATOR" VARCHAR2(5), 
	"VALUE_STRING" VARCHAR2(100), 
	"VALUE_NUMERIC" NUMBER, 
	"VALUE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

