CREATE TABLE "EWALLET_V21"."SALE_ORDER_DETAIL" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ORDER_ID" NUMBER, 
	"ITEM_ID" NUMBER, 
	"QUANTITY" NUMBER, 
	"AMOUNT" NUMBER, 
	 CONSTRAINT "SALE_ORDER_DETAIL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

