CREATE TABLE "EWALLET_V21"."SALE_ORDER" 
   (	"ORDER_ID" NUMBER NOT NULL ENABLE, 
	"TYPE_ID" NUMBER NOT NULL ENABLE, 
	"TRANSACTION_ID" NUMBER NOT NULL ENABLE, 
	"ACCOUNT_ID" NUMBER NOT NULL ENABLE, 
	"MSISDN" VARCHAR2(20), 
	"CUSTOMER_ID" NUMBER, 
	"CUSTOMER_IP_ADDRESS" VARCHAR2(50), 
	"AMOUNT" NUMBER, 
	"DISCOUNT" NUMBER, 
	"TAX" NUMBER, 
	"TOTAL" NUMBER, 
	"CURRENCY" VARCHAR2(5), 
	"STATUS" NUMBER, 
	"EXT_STATUS" VARCHAR2(20), 
	"EXT_ORDER_ID" NUMBER, 
	"EXT_URL" VARCHAR2(500), 
	"DATE_CREATED" DATE, 
	"DATE_UPDATED" DATE, 
	"DATE_PAID" DATE, 
	"DATE_COMPLETED" DATE, 
	"CREATE_USER" VARCHAR2(200), 
	"UPDATE_USER" VARCHAR2(200), 
	 CONSTRAINT "SALE_ORDER_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

