CREATE TABLE "EWALLET_V21"."SALE_STOCK" 
   (	"STOCK_ID" NUMBER NOT NULL ENABLE, 
	"ITEM_ID" NUMBER, 
	"TOTAL_QUANTITY" NUMBER, 
	"STOCK_QUANTITY" NUMBER, 
	"REMAIN_QUANTITY" NUMBER, 
	"DATE_CREATED" DATE, 
	"DATE_UPDATED" DATE, 
	"CREATE_USER" VARCHAR2(200), 
	"UPDATE_USER" VARCHAR2(200), 
	 CONSTRAINT "SALE_STOCK_PK" PRIMARY KEY ("STOCK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

