CREATE TABLE "EWALLET_V21"."SALE_ITEMS" 
   (	"ITEM_ID" NUMBER NOT NULL ENABLE, 
	"SKU" VARCHAR2(20), 
	"NAME" VARCHAR2(500) NOT NULL ENABLE, 
	"UNIT" VARCHAR2(100), 
	"PRICE" NUMBER NOT NULL ENABLE, 
	"MANUFACTURER" VARCHAR2(500), 
	"BRAND" VARCHAR2(500), 
	"SUPPLIER" VARCHAR2(500), 
	"DESCRIPTION" VARCHAR2(2000), 
	"ITEM_SIZE" VARCHAR2(500), 
	"COLOR" VARCHAR2(500), 
	"FILE_ATTACH_ID" NUMBER, 
	"STATUS" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"DATE_CREATED" DATE, 
	"DATE_UPDATED" DATE, 
	"CREATE_USER" VARCHAR2(200), 
	"UPDATE_USER" VARCHAR2(200), 
	 CONSTRAINT "SALE_ITEMS_PK" PRIMARY KEY ("ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

