CREATE TABLE "EWALLET_V21"."SELF_RESET_PIN_VALIDATE_FAIL" 
   (	"PHONE_NUMBER" VARCHAR2(20), 
	"CREATE_DATETIME" DATE, 
	"ROLE_ID" NUMBER(2,0), 
	"IS_LOCKED" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

