CREATE TABLE "EWALLET_V21"."SEND_FLASH_SMS_LOG" 
   (	"DATE_CREATED" DATE, 
	"SEND_TIME" DATE, 
	"STATUS" NUMBER(2,0), 
	"MSISDN" VARCHAR2(25), 
	"TYPE" VARCHAR2(35), 
	"CONTENT" VARCHAR2(1000), 
	"ACCOUNT_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

