CREATE TABLE "EWALLET_V21"."SERVICE_CODE_MAPPING" 
   (	"ID" NUMBER(22,0) NOT NULL DISABLE, 
	"PROCESS_CODE" VARCHAR2(6) NOT NULL ENABLE, 
	"PARTNER_CODE" VARCHAR2(50), 
	"SERVICE_CODE" VARCHAR2(50), 
	"NAME" VARCHAR2(100), 
	"CONTENT" VARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

