CREATE TABLE "EWALLET_V21"."STAFF_MOSAN_D2D_AGENT" 
   (	"STAFF_PHONE" VARCHAR2(20), 
	"PHONE_NUMBER" VARCHAR2(20), 
	"ROLE" VARCHAR2(20), 
	"DISTRICT" VARCHAR2(20), 
	"IS_TOPUP" NUMBER(1,0), 
	"IS_CICO" NUMBER(1,0), 
	"IS_POPA" NUMBER(1,0), 
	"IS_MTO" NUMBER(1,0), 
	"STATUS" NUMBER(1,0), 
	"CREATED_DATE" DATE, 
	"UPDATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(100), 
	"MODIFIED_BY" VARCHAR2(100), 
	"NOTE" VARCHAR2(500), 
	"IS_POS" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

