CREATE TABLE "EWALLET_V21"."SUB_MB_BLOCK2WAY" 
   (	"SUB_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CUST_ID" NUMBER(38,0), 
	"ISDN" VARCHAR2(10), 
	"STATUS" NUMBER(1,0), 
	"ACT_STATUS" VARCHAR2(2), 
	"STA_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"FINISH_REASON_ID" NUMBER(10,0), 
	"REG_TYPE" VARCHAR2(15), 
	"VIP" VARCHAR2(1), 
	"USER_CREATED" VARCHAR2(50), 
	"SHOP_CODE" VARCHAR2(50), 
	"OFFER_ID" NUMBER(10,0), 
	"SUB_NAME" VARCHAR2(200), 
	"BIRTH_DATE" DATE, 
	"GENDER" CHAR(1), 
	"PROVINCE" VARCHAR2(4), 
	"DISTRICT" VARCHAR2(3), 
	"PRECINCT" VARCHAR2(4), 
	"ADDRESS" VARCHAR2(255), 
	"SUBCOS_HUAWEI" VARCHAR2(10), 
	"SUBCOS_ZTE" VARCHAR2(50), 
	"START_MONEY" VARCHAR2(10), 
	"IMSI" VARCHAR2(15), 
	"SERIAL" VARCHAR2(20), 
	"PASSWORD" VARCHAR2(32), 
	"VALID_DATETIME" DATE, 
	"CHANGE_DATETIME" DATE, 
	"PROMOTION_CODE" VARCHAR2(3), 
	"FIRST_EXP_DATE" DATE, 
	"SECOND_EXP_DATE" DATE, 
	"NOTES" VARCHAR2(200), 
	"FIRST_SHOP_CODE" VARCHAR2(50), 
	"PROM_VALID_DATETIME" DATE, 
	"PRODUCT_CODE" VARCHAR2(30), 
	"ORG_PRODUCT_CODE" VARCHAR2(30), 
	"LAST_NUMBER" CHAR(1), 
	"NUM_RESET_ZONE" NUMBER(10,0), 
	"IS_TRANSFER" VARCHAR2(10), 
	"SIM_TYPE" VARCHAR2(50), 
	"CHANGE_SIM_4G_FREE" NUMBER(10,0), 
	"STATUS_CHECK" NUMBER(2,0), 
	"LANGUAGE" VARCHAR2(10 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

