CREATE TABLE "EWALLET_V21"."SYN_DATA_TO_PREPAID_TEMP" 
   (	"MSISDN" VARCHAR2(20), 
	"ID_NO" VARCHAR2(20), 
	"FULL_NAME" VARCHAR2(50), 
	"BIRTHDAY" DATE, 
	"ADDRESS" VARCHAR2(200), 
	"CREATE_DATE" DATE, 
	"ID_TYPE" VARCHAR2(30), 
	"GENDER" VARCHAR2(20), 
	"EXPIRE_DATE" DATE, 
	"PHONE_TYPE" NUMBER(1,0), 
	"ISSUE_DATE" DATE, 
	"AGENT_CODE" VARCHAR2(50), 
	"AGENT_NAME" VARCHAR2(250), 
	"CC_APPROVE_SEND" VARCHAR2(50), 
	"CC_APPROVE_RECEIVE" VARCHAR2(50), 
	"TYPE" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

