CREATE TABLE "EWALLET_V21"."SYNC_DATA" 
   (	"SYNC_START_TIME" TIMESTAMP (6) DEFAULT NULL, 
	"SYNC_END_TIME" TIMESTAMP (6) DEFAULT NULL, 
	"ID" NUMBER, 
	"EXECUTE_TIME" NUMBER NOT NULL ENABLE, 
	"SYNC_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"CONDITION_FILTER" VARCHAR2(200), 
	"SYNC_FIRST_TIME" TIMESTAMP (6) DEFAULT sysdate, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

