CREATE TABLE "EWALLET_V21"."SYNC_VIEW" 
   (	"VIEW_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"TRANSACTION_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"CREATED_AT" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

