CREATE TABLE "EWALLET_V21"."SYS_USER" 
   (	"VALUE" VARCHAR2(50), 
	"TYPE" NUMBER(2,0), 
	"PARTY_ID" NUMBER, 
	"ROLE_ID" NUMBER, 
	"PARTY_ROLE_ID" NUMBER, 
	"PARTY_ROLE_PARENT_ID" NUMBER, 
	"ACCOUNT_PARENT_ID" NUMBER, 
	"MAC" VARCHAR2(50), 
	"LAST_LOGIN" DATE, 
	"FAILED_COUNTER" NUMBER DEFAULT 0, 
	"IP" VARCHAR2(20), 
	"LAST_LOGIN_FAIL" DATE, 
	"LAST_LOGIN_IP" VARCHAR2(50), 
	"CREATED_BY" VARCHAR2(20), 
	"STAFF_ID" NUMBER(20,0), 
	"PREFERRED_LANGUAGE" VARCHAR2(5), 
	"CREATED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

