CREATE TABLE "EWALLET_V21"."TARIFF_PLAN_MAPPING" 
   (	"TARIFF_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"TARIFF_PLAN_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"STATUS" NUMBER(1,0) DEFAULT 1, 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(20), 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 2 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

