CREATE TABLE "EWALLET_V21"."TARIFF_EXTEND_ITEM" 
   (	"TARIFF_EXTEND_ITEM_ID" NUMBER NOT NULL ENABLE, 
	"TARIFF_NAME" VARCHAR2(100), 
	"TARIFF_DESCRIPTION" VARCHAR2(200), 
	"CONDITION" VARCHAR2(500), 
	"DATE_CREATED" DATE, 
	"USER_CREATED" VARCHAR2(100), 
	 PRIMARY KEY ("TARIFF_EXTEND_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 2 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

