CREATE TABLE "EWALLET_V21"."TARIFF_EXTEND_CONFIG" 
   (	"TARIFF_EXTEND_CONFIG_ID" NUMBER NOT NULL ENABLE, 
	"ACCOUNT_ID" NUMBER, 
	"ROLE_ID" NUMBER, 
	"TIER" NUMBER, 
	"ACCOUNT_TYPE_ID" NUMBER, 
	"STATUS" NUMBER, 
	"PROCESS_CODE" VARCHAR2(6), 
	"VALID_FROM" DATE, 
	"VALID_TO" DATE, 
	"TARIFF_EXTEND_ITEM_ID" NUMBER, 
	"FROM_VALUE" NUMBER, 
	"TO_VALUE" NUMBER, 
	"TARIFF_ITEM_ID" NUMBER, 
	"VALUE_TYPE" NUMBER, 
	"MIN_VALUE" NUMBER, 
	"MAX_VALUE" NUMBER, 
	"VALUE" NUMBER, 
	"CURRENCY_CODE" VARCHAR2(6), 
	"TARIFF_TYPE" NUMBER, 
	"APPLY_FOR" NUMBER, 
	"DATE_CREATED" DATE, 
	"USER_CREATED" VARCHAR2(100), 
	"TARIFF_PLAN_ID" NUMBER, 
	"PRIORITY" NUMBER, 
	"PARTNER_CODE" VARCHAR2(100), 
	"SERVICE_CODE" VARCHAR2(100), 
	 CONSTRAINT "TARIFF_EXTEND_TARIFF_TYPE" CHECK (TARIFF_TYPE IN (1,2)) DEFERRABLE ENABLE, 
	 CONSTRAINT "TARIFF_EXTEND_PK" PRIMARY KEY ("TARIFF_EXTEND_CONFIG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 2 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

