CREATE TABLE "EWALLET_V21"."TARIFF" 
   (	"TARIFF_ID" NUMBER(8,0) NOT NULL DISABLE, 
	"NAME" VARCHAR2(100 CHAR) NOT NULL DISABLE, 
	"VALUE_TYPE" NUMBER(8,0) NOT NULL DISABLE, 
	"MIN_VALUE" NUMBER(15,2), 
	"MAX_VALUE" NUMBER(15,2), 
	"VALUE" NUMBER(15,2) NOT NULL DISABLE, 
	"CREATED_DATE" DATE NOT NULL DISABLE, 
	"INCENTIVE" NUMBER(15,2), 
	"FROM_VALUE" NUMBER(15,2), 
	"TO_VALUE" NUMBER(15,2), 
	"PROCESS_CODE" VARCHAR2(6) NOT NULL DISABLE, 
	"TARIFF_ITEM_ID" NUMBER(8,0) NOT NULL DISABLE, 
	"APPLY_TYPE" NUMBER(1,0) NOT NULL ENABLE, 
	"APPLY_TO" NUMBER(1,0), 
	"PRIORITY" NUMBER(2,0), 
	"PARTNER_CODE" VARCHAR2(100), 
	"SERVICE_CODE" VARCHAR2(100), 
	 CONSTRAINT "PK_TF" PRIMARY KEY ("TARIFF_ID") DISABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 2 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

