CREATE TABLE "EWALLET_V21"."TARIFF_PLAN_SPECIFIC_310519" 
   (	"TARIFF_PLAN_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"ACCOUNT_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"STATUS" NUMBER(5,0), 
	"VALID_FROM" DATE, 
	"VALID_TO" DATE, 
	"PLAN_NAME" VARCHAR2(50), 
	"VERSION" VARCHAR2(10), 
	"PIORITY" NUMBER(3,0), 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(20), 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

