CREATE TABLE "EWALLET_V21"."TEMP_SEND_MESS_CHRISTMAS" 
   (	"MSISDN" VARCHAR2(20), 
	"NUM_SEND_MESS" NUMBER(1,0), 
	"DAY_SEND" NUMBER(2,0), 
	"CREATED_DATE" DATE, 
	"MODIFIED_DATE" DATE, 
	"MESS_TYPE" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

