CREATE TABLE "EWALLET_V21"."TEMP_CUS_BUY_PACKAGE" 
   (	"REQUEST_DATE" DATE NOT NULL ENABLE, 
	"MSISDN" VARCHAR2(20), 
	"VAS_CODE" VARCHAR2(10), 
	"CARRIED_PHONE" VARCHAR2(20), 
	"AMOUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

