CREATE TABLE "EWALLET_V21"."TEMP_BONUS_SERVICE" 
   (	"ACCOUNT_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"MSISDN" VARCHAR2(20), 
	"LAST_NAME" VARCHAR2(100), 
	"ROLE_NAME" VARCHAR2(50), 
	"BALANCE" NUMBER, 
	"ACCOUNT_STATE" VARCHAR2(100) NOT NULL ENABLE, 
	"STATUS" NUMBER, 
	"CREATED_DATE" DATE, 
	"MODIFIED_DATE" DATE, 
	"NOTE" VARCHAR2(500), 
	"ERR_CODE" VARCHAR2(20), 
	"REQ_ID" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

