CREATE TABLE "EWALLET_V21"."TEMP_FINISH_TRANS_TEMP" 
   (	"ACTION_ID" NUMBER(22,0), 
	"FROM_ACC_ID" NUMBER(22,0), 
	"PROCESS_CODE" VARCHAR2(6) NOT NULL ENABLE, 
	"DATE_CREATED" DATE NOT NULL ENABLE, 
	"TRANSACTION_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"AMOUNT" NUMBER(30,5) NOT NULL ENABLE, 
	"STATUS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

