CREATE TABLE "EWALLET_V21"."TEMP_DATA_ALL_CUS" 
   (	"ROLE_NAME" VARCHAR2(50), 
	"LAST_NAME" VARCHAR2(100), 
	"MSISDN" VARCHAR2(20), 
	"ACCOUNT_STATE_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"ACTIVE_TIME" DATE, 
	"DISTRICT" VARCHAR2(50), 
	"BALANCE" NUMBER, 
	"DATE_MAKE_TRANSACTION" DATE, 
	"DATE_BLOCK_2_WAY" DATE, 
	"MOBILE_STATUS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

