CREATE TABLE "EWALLET_V21"."TEMP_CANCEL_ACCOUNT_0324" 
   (	"ACCOUNT_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"MSISDN" VARCHAR2(20), 
	"PARTY_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"PARTY_ROLE_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"ACTIVE_TIME" DATE, 
	"LAST_NAME" VARCHAR2(100), 
	"ACCOUNT_STATE_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"CREATED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

