CREATE TABLE "EWALLET_V21"."TEMP_RP_TRANS_BY_GENDER" 
   (	"NAME" VARCHAR2(21), 
	"MEN_VOLUME" NUMBER, 
	"MEN_AMOUNT" NUMBER, 
	"WOMAN_VOLUME" NUMBER, 
	"WOMAN_AMOUNT" NUMBER, 
	"OTHER_VOLUME" NUMBER, 
	"OTHER_AMOUNT" NUMBER, 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

