CREATE TABLE "EWALLET_V21"."TEMP_FORCE_UPDATE_APP" 
   (	"MSISDN" VARCHAR2(20), 
	"TYPE" VARCHAR2(50), 
	"ROLE" VARCHAR2(20), 
	"STATUS" NUMBER, 
	"CREATED_DATE" DATE, 
	"UPDATED_DATE" DATE, 
	"NODE" VARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

