CREATE TABLE "EWALLET_V21"."TEXT_MT" 
   (	"TEXT_MT_ID" NUMBER(20,0), 
	"MT_CONTENT" VARCHAR2(1024), 
	"PROCESS_TIME" TIMESTAMP (6), 
	"STATUS" NUMBER(3,0) DEFAULT 0, 
	"ISDN" VARCHAR2(20), 
	"SENDER" VARCHAR2(20), 
	"CREATETIME" DATE, 
	"FLAG" NUMBER, 
	"UPDATE_TIME" DATE, 
	"RETRYTIMES" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

