CREATE TABLE "EWALLET_V21"."TOKEN" 
   (	"UUID" VARCHAR2(64) NOT NULL ENABLE, 
	"ACCESS_TOKEN" VARCHAR2(64) NOT NULL ENABLE, 
	"VALID_FROM" DATE NOT NULL ENABLE, 
	"VALID_TO" DATE NOT NULL ENABLE, 
	"REFRESH_TOKEN" VARCHAR2(64), 
	"TOKEN_TYPE" VARCHAR2(20) NOT NULL ENABLE, 
	"ACCOUNT_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"ID" NUMBER(12,0), 
	"PROCESSING_CODE" VARCHAR2(6), 
	 UNIQUE ("ACCOUNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

