CREATE TABLE "EWALLET_V21"."TRANS_ACCOUNTING_PENDING" 
   (	"TRANS_ACCOUNTING_ID" NUMBER NOT NULL ENABLE, 
	"TRANSACTION_ID" NUMBER(17,0) NOT NULL ENABLE, 
	"ACTION_ID" NUMBER(17,0), 
	"PROCESS_CODE" VARCHAR2(6) NOT NULL ENABLE, 
	"TRANS_TYPE_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"ACTION_NODE_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"FROM_ACC_ID" NUMBER(8,0), 
	"FROM_PARTY_ROLE_ID" NUMBER(12,0), 
	"TO_ACC_ID" NUMBER(8,0), 
	"TO_PARTY_ROLE_ID" NUMBER(12,0), 
	"AMOUNT" NUMBER(30,5) NOT NULL ENABLE, 
	"CURRENCY_CODE" VARCHAR2(5) NOT NULL ENABLE, 
	"DATE_CREATED" DATE NOT NULL ENABLE, 
	"ACCOUNTING_TYPE_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"TRANS_STATE_ID" NUMBER(8,0) DEFAULT null, 
	"STATUS" NUMBER(2,0) NOT NULL ENABLE, 
	"ERROR_CODE" VARCHAR2(5), 
	"ERROR_DES" VARCHAR2(2000), 
	"TRANS_COMMISSION_ID" NUMBER(12,0), 
	"TRANS_AMOUNT" NUMBER(30,5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS  LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
  PARTITION BY RANGE ("DATE_CREATED") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) 
 (PARTITION "LOG_DATA_P1"  VALUES LESS THAN (TO_DATE(' 2017-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ) ;

