CREATE TABLE "EWALLET_V21"."TRANS_ACCOUNTING" 
   (	"TRANS_ACCOUNTING_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"TRANSACTION_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"ACTION_ID" NUMBER(22,0), 
	"PROCESS_CODE" VARCHAR2(6) NOT NULL ENABLE, 
	"TRANS_TYPE_ID" NUMBER(22,0), 
	"ACTION_NODE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"FROM_ACC_ID" NUMBER(22,0), 
	"FROM_PARTY_ROLE_ID" NUMBER(22,0), 
	"TO_ACC_ID" NUMBER(22,0), 
	"TO_PARTY_ROLE_ID" NUMBER(22,0), 
	"AMOUNT" NUMBER(30,5) NOT NULL ENABLE, 
	"CURRENCY_CODE" VARCHAR2(5) NOT NULL ENABLE, 
	"DATE_CREATED" DATE NOT NULL ENABLE, 
	"ACCOUNTING_TYPE_ID" NUMBER(22,0), 
	 CONSTRAINT "TRANS_ACCOUNTING_PK" PRIMARY KEY ("TRANS_ACCOUNTING_ID")
  USING INDEX PCTFREE 10 INITRANS 4 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS  LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
  PARTITION BY RANGE ("DATE_CREATED") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) 
 (PARTITION "LOG_DATA_P1"  VALUES LESS THAN (TO_DATE(' 2017-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" )  ENABLE ROW MOVEMENT ;

