CREATE TABLE "EWALLET_V21"."TRANS_TAX" 
   (	"TRANS_TAX_ID" NUMBER, 
	"LIMITATION" NUMBER, 
	"PROCESS_CODE" VARCHAR2(6), 
	"TRANSACTION_ID" NUMBER, 
	"VALUE" NUMBER, 
	"TAX_MONEY" NUMBER, 
	"TAX_DATE" DATE, 
	"TRANS_AMOUNT" NUMBER, 
	"CREATE_DATE" DATE, 
	"TRANSACTION_ID_REF" NUMBER, 
	"TAX_STATUS" VARCHAR2(20), 
	"VALUE_TYPE" NUMBER DEFAULT 1, 
	"ACCOUNT_ID" NUMBER, 
	"ACTION_ID_REF" NUMBER, 
	"TAX_TYPE" VARCHAR2(50), 
	"TRANS_COMMISSION_ID" NUMBER, 
	"REASON" VARCHAR2(1000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

