CREATE TABLE "EWALLET_V21"."TRANSACTION_FACT_DAILY" 
   (	"FACT_DATE" DATE NOT NULL ENABLE, 
	"ACCOUNT_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"TOTAL_CREDIT" NUMBER(34,5) DEFAULT 0, 
	"TOTAL_DEBIT" NUMBER(34,5) DEFAULT 0, 
	"TOTAL_TRANSFER" NUMBER(34,5) DEFAULT 0, 
	"TOTAL_ENQUIRY" NUMBER(34,5) DEFAULT 0, 
	"TOTAL_LOGIN" NUMBER(8,0) DEFAULT 0, 
	"TOTAL_TRANSFER_FAIL" NUMBER(8,0) DEFAULT 0, 
	"TOTAL_TRANSFER_BLOCK" NUMBER(8,0) DEFAULT 0, 
	"TOTAL_LOGIN_FAIL" NUMBER(8,0) DEFAULT 0, 
	"TOTAL_ACTION" NUMBER(8,0) DEFAULT 0, 
	"OPENING_BALANCE" NUMBER(18,6) DEFAULT 0, 
	"CLOSING_BALANCE" NUMBER(18,6) DEFAULT 0, 
	 CONSTRAINT "UK_TFDY" UNIQUE ("FACT_DATE", "ACCOUNT_ID")
  USING INDEX PCTFREE 10 INITRANS 4 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS  LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
  PARTITION BY RANGE ("FACT_DATE") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) 
 (PARTITION "LOG_DATA_P1"  VALUES LESS THAN (TO_DATE(' 2017-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ) ;

