CREATE TABLE "EWALLET_V21"."TRANS_PERMIT_CONFIG" 
   (	"PROCESS_CODE" VARCHAR2(6) NOT NULL ENABLE, 
	"TRANS_STATE_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"TRANS_PERMIT_CONFIG_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"PARTNER_CONFIG_ID" NUMBER(22,0), 
	"EFFECT_TYPE" NUMBER(1,0), 
	 CONSTRAINT "TRANS_PERMIT_CONFIG_PK" PRIMARY KEY ("TRANS_PERMIT_CONFIG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

