CREATE TABLE "EWALLET_V21"."TRANS_WESTERN_UNION" 
   (	"ACTION_ID" NUMBER(14,0) NOT NULL ENABLE, 
	"TRANSACTION_ID" NUMBER(12,0), 
	"PROCESS_CODE" VARCHAR2(6), 
	"RECEIVER_NAME" VARCHAR2(50), 
	"RECEIVER_PHONE" VARCHAR2(50), 
	"DATE_OF_BIRTH" DATE, 
	"GENDER" VARCHAR2(10), 
	"PAPER_TYPE" VARCHAR2(50), 
	"PAPER_NUMBER" VARCHAR2(50), 
	"ISSUED_DATE" DATE, 
	"EXPIRED_DATE" DATE, 
	"PLACE_OF_ISSUED" VARCHAR2(200), 
	"ADDRESS" VARCHAR2(200), 
	"MTCN_CODE" VARCHAR2(50), 
	"ORG_AMOUNT" NUMBER(30,5), 
	"AMOUNT" NUMBER(30,5), 
	"TO_CURRENCY" VARCHAR2(20), 
	"ORG_CURRENCY" VARCHAR2(20), 
	"EX_RATE" NUMBER(3,2), 
	"CONTENT" VARCHAR2(200), 
	"ACTION_STATE" NUMBER(2,0), 
	"REFER_ACTION_ID" NUMBER(14,0), 
	"CARRIED_PHONE" VARCHAR2(20), 
	"CARRIED_ACCOUNT" NUMBER(14,0), 
	"CARRIED_NAME" VARCHAR2(100), 
	"CREATED_DATE" DATE, 
	"LAST_MODIFIED" DATE, 
	"APPROVED_BY" VARCHAR2(100), 
	"REVIEWED_BY" VARCHAR2(100), 
	"APPROVED_DATE" DATE, 
	"REVIEWED_DATE" DATE, 
	"REASON_REJECT" VARCHAR2(200), 
	"CARRIED_CODE" VARCHAR2(100), 
	"AREA_NAME" VARCHAR2(50), 
	"FEE" NUMBER(30,5) DEFAULT 0, 
	"COMMISSION_FOR_AGENT" NUMBER(30,5) DEFAULT 0, 
	 CONSTRAINT "PK_TRANS_WESTERN_UNION" PRIMARY KEY ("ACTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

