CREATE TABLE "EWALLET_V21"."TRANS_BATCH" 
   (	"TRANS_BATCH_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"BATCH_TYPE" NUMBER, 
	"PAYMENT_PERIOD" VARCHAR2(20), 
	"DATE_CREATED" DATE, 
	"DATE_MODIFIED" DATE, 
	"CARRIED_CODE" VARCHAR2(50), 
	"DOCUMENT" VARCHAR2(200), 
	"FILE_NAME" VARCHAR2(200), 
	"DESCRIPTION" VARCHAR2(200), 
	"CLIENT_IP" VARCHAR2(50), 
	"USER_APPROVAL" VARCHAR2(50), 
	"DATE_APPROVAL" DATE, 
	"TRANS_BATCH_STATE" NUMBER(2,0), 
	"DENY_REASON" VARCHAR2(200), 
	"TOTAL" NUMBER(5,0), 
	"TOTAL_ERR" NUMBER(5,0), 
	"TOTAL_SUCCESS" NUMBER(5,0), 
	 CONSTRAINT "TRANS_BATCH_PK" PRIMARY KEY ("TRANS_BATCH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

