CREATE TABLE "EWALLET_V21"."TRANS_BATCH_DETAIL" 
   (	"ID" NUMBER(22,0) NOT NULL ENABLE, 
	"TRANS_BATCH_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"TRANSACTION_ID" NUMBER(22,0), 
	"GROUP_TYPE" NUMBER(1,0), 
	"PROCESS_CODE" VARCHAR2(6), 
	"BATCH_TYPE" NUMBER(1,0), 
	"FROM_ACC_ID" NUMBER(12,0), 
	"FROM_PHONE" VARCHAR2(20), 
	"TO_ACC_ID" NUMBER(12,0), 
	"TO_PHONE" VARCHAR2(20), 
	"AMOUNT" NUMBER(12,5), 
	"DESCRIPTION" VARCHAR2(200), 
	"TRANSFER_TYPE" NUMBER(1,0), 
	"TOTAL_STEP" NUMBER(1,0), 
	"TRANS_STATE" NUMBER(2,0), 
	"PROCESS_STATE" NUMBER(1,0), 
	"PAYMENT_NO" VARCHAR2(20), 
	"DATE_CREATED" DATE, 
	"CREATED_BY" VARCHAR2(20), 
	"DATE_REVIEWED" DATE, 
	"REVIEWED_BY" VARCHAR2(20), 
	"DATE_APPROVED" DATE, 
	"APPROVED_BY" VARCHAR2(20), 
	"DATE_MODIFIED" DATE, 
	"MODIFIED_BY" VARCHAR2(20), 
	"SOURCE" VARCHAR2(250)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

