CREATE TABLE "EWALLET_V21"."TRANSACTION_FOR_TARIFF_134263" 
   (	"TRANSACTION_ID" NUMBER, 
	"ACCOUNT_ID" NUMBER, 
	"ACCOUNT_PHONE" VARCHAR2(20), 
	"ACCOUNT_NAME" VARCHAR2(100), 
	"PARTY_ROLE_ID" NUMBER, 
	"AMOUNT" NUMBER, 
	"DISCOUNT" NUMBER, 
	"FEE" NUMBER, 
	"COMMISSION" NUMBER, 
	"TOTAL_AMOUNT" NUMBER, 
	"PROCESS_CODE" VARCHAR2(6), 
	"TRANSACTION_STATE_ID" NUMBER, 
	"DATE_CREATED" DATE, 
	"CURRENCY" VARCHAR2(3), 
	"ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "TRANSACTION_FOR_TARIFF_134_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

