CREATE TABLE "EWALLET_V21"."TRANS_BCCS_SYNC_LOG" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TABLE_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"DATE_CREATED" DATE NOT NULL ENABLE, 
	"DATE_MODIFIED" DATE, 
	"SYNC_FROM" DATE, 
	"SYNC_TO" DATE, 
	"STATUS" NUMBER, 
	"TRANS_COUNT" NUMBER, 
	 CONSTRAINT "TRANS_BCCS_SYNC_LOG_PK_IDX" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "EWALLET_V21"."TRANS_BCCS_SYNC_LOG_PK1" ON "EWALLET_V21"."TRANS_BCCS_SYNC_LOG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" )  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

