CREATE TABLE "EWALLET_V21"."TRANS_VPG_BONUS" 
   (	"REQ_PAYMENT_ID" NUMBER NOT NULL ENABLE, 
	"ACTION_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PROCESS_CODE" VARCHAR2(6) NOT NULL ENABLE, 
	"CARRIED_ACCOUNT_ID" NUMBER(38,0), 
	"MSISDN" VARCHAR2(20), 
	"REQUEST_DATE" DATE NOT NULL ENABLE, 
	"RESPONSE_DATE" DATE, 
	"RESPONSE_CODE" VARCHAR2(3), 
	"AMOUNT" NUMBER(38,5), 
	"ACTION_NODE_ID" NUMBER(8,0), 
	"REQUEST_CONTENT" VARCHAR2(3000), 
	"RESPONSE_CONTENT" VARCHAR2(3000), 
	"TRANSACTION_ID" NUMBER(22,0), 
	"ERROR_CODE" VARCHAR2(20), 
	"RESPONSE_ERROR_CODE" NUMBER(2,0), 
	"RESPONSE_DESC" VARCHAR2(200), 
	"PARTNER_CODE" VARCHAR2(30), 
	"SERVICE_CODE" VARCHAR2(30), 
	"REQUEST_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"TRANSACTION_STATE_ID" NUMBER(38,0), 
	 PRIMARY KEY ("REQ_PAYMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

