CREATE TABLE "EWALLET_V21"."TRANS_FINANCE" 
   (	"ACTION_ID" NUMBER NOT NULL ENABLE, 
	"ACTION_NODE_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"FROM_PHONE" VARCHAR2(20), 
	"FROM_PARTY_ROLE" NUMBER(12,0), 
	"FROM_ID" NUMBER(12,0), 
	"TO_PHONE" VARCHAR2(20), 
	"TO_PARTY_ROLE" NUMBER(12,0), 
	"TO_ID" NUMBER(12,0), 
	"AMOUNT" NUMBER(30,5), 
	"ORG_AMOUNT" NUMBER(30,5), 
	"FEE" NUMBER(30,5), 
	"TOTAL_AMOUNT" NUMBER(30,5), 
	"FROM_CURRENCY" VARCHAR2(3) NOT NULL ENABLE, 
	"TO_CURRENCY" VARCHAR2(3), 
	"EXCHANGE_RATE" NUMBER, 
	"REQUEST_REASON" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"REQUEST_USER" VARCHAR2(20), 
	"DATE_CREATED" DATE, 
	"DATE_MODIFIED" DATE, 
	"BANK_TRANSID" VARCHAR2(50), 
	"BANK_CODE" VARCHAR2(50), 
	"BANK_NAME" VARCHAR2(50), 
	"BRANCH_BANK" VARCHAR2(50), 
	"BANK_ACCOUNTNO" VARCHAR2(50), 
	"REFER_PHONE" VARCHAR2(20), 
	"ACTION_STATE_ID" NUMBER(8,0), 
	"APPROVED_AMOUNT" NUMBER(30,5), 
	"REJECT_REASON" VARCHAR2(100), 
	"CLIENT_IP" VARCHAR2(20), 
	"APPROVED_USER" VARCHAR2(20), 
	"REFER_ID" VARCHAR2(20), 
	"SERVICE_CODE" VARCHAR2(20), 
	"PROCESS_CODE" VARCHAR2(6), 
	"REQUEST_APPROVED_DATE" DATE, 
	"REQUEST_NO" VARCHAR2(50), 
	"FROM_CURRENCY_ID" NUMBER(8,0), 
	"TO_CURRENCY_ID" NUMBER(8,0), 
	"BANK_TIME" DATE, 
	"TRANSACTION_ID" NUMBER(12,0), 
	"PARTY_ROLE_PARENT_ID" NUMBER(20,0), 
	"IS_REVIEW" VARCHAR2(20), 
	"REVIEWED_USER" VARCHAR2(50), 
	"REVIEW_TIME" DATE, 
	"REVIEW_BY" NVARCHAR2(30) DEFAULT null, 
	 CONSTRAINT "TRANSACTION_FINANCE_NEW_PK" PRIMARY KEY ("ACTION_ID")
  USING INDEX PCTFREE 10 INITRANS 4 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
  PARTITION BY RANGE ("DATE_CREATED") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) 
 (PARTITION "LOG_DATA_P1"  VALUES LESS THAN (TO_DATE(' 2017-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ) ;

