CREATE TABLE "EWALLET_V21"."TRANS_STATE_GROUP" 
   (	"TRANS_STATE_GROUP_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(20), 
	"DESCRIPTION" VARCHAR2(100), 
	 CONSTRAINT "TRANS_STEP_STATE_PK" PRIMARY KEY ("TRANS_STATE_GROUP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

