CREATE TABLE "EWALLET_V21"."TRANS_VPG" 
   (	"REQ_PAYMENT_ID" NUMBER NOT NULL ENABLE, 
	"ACTION_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PROCESS_CODE" VARCHAR2(6) NOT NULL ENABLE, 
	"CARRIED_ACCOUNT_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"REQ_MSISDN" VARCHAR2(20), 
	"MSISDN" VARCHAR2(20), 
	"CUST_CODE" VARCHAR2(20), 
	"REQUEST_DATE" DATE NOT NULL ENABLE, 
	"RESPONSE_DATE" DATE, 
	"RESPONSE_CODE" VARCHAR2(3), 
	"AMOUNT" NUMBER(38,5), 
	"TOTAL_AMOUNT" NUMBER(38,5), 
	"ACTION_NODE_ID" NUMBER(8,0), 
	"REQUEST_CONTENT" VARCHAR2(3000), 
	"RESPONSE_CONTENT" VARCHAR2(3000), 
	"CORRECT_RESPONSE_CODE" VARCHAR2(3), 
	"RECON_RESULT" VARCHAR2(3), 
	"MORE_DETAIL" VARCHAR2(300), 
	"MODIFIED_DATE" DATE, 
	"CORRECT_CODE" VARCHAR2(3), 
	"CORRECT_SOURCE" VARCHAR2(3), 
	"CORRECT_DATE" DATE, 
	"CORRECT_REASON" VARCHAR2(200), 
	"FILE_IMPORT_NAME" VARCHAR2(50), 
	"TRANSACTION_ID" NUMBER(22,0), 
	"ERROR_CODE" VARCHAR2(20), 
	"RESPONSE_ERROR_CODE" NUMBER(2,0), 
	"RESPONSE_DESC" VARCHAR2(200), 
	"PARTNER_CODE" VARCHAR2(30), 
	"SERVICE_CODE" VARCHAR2(30), 
	"VAS_CODE" VARCHAR2(10), 
	"VAS_SHORT_CODE" VARCHAR2(5), 
	"HISTORY_ID" NUMBER, 
	"ACTION_TYPE" NUMBER(2,0), 
	"CLUSTER_NAME" VARCHAR2(30), 
	"RESPONSE_INFO" VARCHAR2(200), 
	"NODE_NAME" VARCHAR2(30), 
	"PRODUCT_CODE" VARCHAR2(30), 
	"RECON_COUNT" NUMBER, 
	 CONSTRAINT "TRANS_VPG_LOG_NEW_PK" PRIMARY KEY ("REQ_PAYMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 4 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
  PARTITION BY RANGE ("REQUEST_DATE") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) 
 (PARTITION "LOG_DATA_P1"  VALUES LESS THAN (TO_DATE(' 2017-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ) ;

