CREATE TABLE "EWALLET_V21"."TRANS_WESTERN_UNION_BATCH" 
   (	"ID" NUMBER(12,0), 
	"BATCH_NAME" VARCHAR2(50), 
	"TRANSACTION_ID" NUMBER(12,0), 
	"PROCESS_CODE" VARCHAR2(6), 
	"STATUS" NUMBER(2,0), 
	"REASON_REJECT" VARCHAR2(200), 
	"TOTAL_TRANS" NUMBER(12,0), 
	"TOTAL_AMOUNT" NUMBER(30,5), 
	"CREATED_USER" NVARCHAR2(100), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "PK_TRANS_WESTERN_UNION_BATCH" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

