CREATE TABLE "EWALLET_V21"."TRANSACTION" 
   (	"TRANSACTION_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"FROM_ACC_ID" NUMBER(22,0), 
	"FROM_PHONE" VARCHAR2(20), 
	"FROM_NAME" VARCHAR2(250), 
	"FROM_PARTY_ROLE_ID" VARCHAR2(22), 
	"TO_ACC_ID" NUMBER(22,0), 
	"TO_PHONE" VARCHAR2(20), 
	"TO_NAME" VARCHAR2(250), 
	"TO_PARTY_ROLE_ID" NUMBER(22,0), 
	"AMOUNT" NUMBER(30,5) DEFAULT 0, 
	"DISCOUNT" NUMBER(30,5) DEFAULT 0, 
	"FEE" NUMBER(30,5) DEFAULT 0, 
	"COMMISSION" NUMBER(30,5) DEFAULT 0, 
	"TOTAL_AMOUNT" NUMBER(30,5) DEFAULT 0, 
	"REVENUE_SHARED" NUMBER(30,5) DEFAULT 0, 
	"CURRENCY" VARCHAR2(3) DEFAULT 840, 
	"TRANS_TYPE_ID" NUMBER(22,0), 
	"TRANSACTION_STATE_ID" NUMBER(22,0), 
	"ACTION_NODE_ID" NUMBER(8,0), 
	"CARRIED_NAME" VARCHAR2(250), 
	"CARRIED_ACC_ID" NUMBER(22,0), 
	"CARRIED_CODE" VARCHAR2(50), 
	"REASON_ID" NUMBER(22,0), 
	"CONTENT" NVARCHAR2(2000), 
	"REASON_CONTENT" NVARCHAR2(500), 
	"PARTNER_ID" NUMBER(22,0), 
	"DATE_CREATED" DATE, 
	"DATE_MODIFIED" DATE, 
	"DATE_EXPIRIED" DATE, 
	"DATE_DEADLINE" DATE, 
	"DATE_FINISHED" DATE, 
	"TARIFF_PLAN_ID" NUMBER(10,0), 
	"CARRIED_PHONE" VARCHAR2(20), 
	"PARTNER_CODE" VARCHAR2(100), 
	"SERVICE_CODE" VARCHAR2(100), 
	"ADDITIONAL_DATA" VARCHAR2(4000), 
	 CONSTRAINT "TRANSACTION_PK" PRIMARY KEY ("TRANSACTION_ID")
  USING INDEX PCTFREE 10 INITRANS 4 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS  LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
  PARTITION BY RANGE ("DATE_CREATED") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) 
 (PARTITION "LOG_DATA_P1"  VALUES LESS THAN (TO_DATE(' 2017-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" )  ENABLE ROW MOVEMENT ;

