CREATE TABLE "EWALLET_V21"."TRANS_PROCESS_CODE" 
   (	"PROCESS_CODE" VARCHAR2(6) NOT NULL ENABLE, 
	"TRANS_TYPE_ID" NUMBER(22,0), 
	"NAME" VARCHAR2(250) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(500), 
	"LOCALE_KEY" VARCHAR2(10), 
	"TABLE_NAME" VARCHAR2(250), 
	"SECRET_CODE" VARCHAR2(6), 
	"PAYMENT_BONUS" NUMBER(1,0) NOT NULL ENABLE, 
	"DAY_DEADLINED" NUMBER(2,0), 
	"TRANS_GROUP_ID" NUMBER(2,0), 
	"TARIFF_APPLY_FROM" VARCHAR2(6), 
	"MAPPING_RESPONSE" NUMBER, 
	 CONSTRAINT "TRANS_PROCESS_CODE_PK" PRIMARY KEY ("PROCESS_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 2 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

