CREATE TABLE "EWALLET_V21"."TRANS_MERCHANT_20200303" 
   (	"TRANS_MERCHANT_ID" NUMBER NOT NULL ENABLE, 
	"TRANSACTION_ID" NUMBER(22,0), 
	"ACTION_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"REQUEST_ID" NUMBER, 
	"PROCESS_CODE" VARCHAR2(6) NOT NULL ENABLE, 
	"ACTION_NODE_ID" NUMBER(8,0), 
	"CARRIED_ACCOUNT_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"MERCHANT_TYPE" NUMBER(10,0), 
	"PARTNER_CODE" VARCHAR2(20), 
	"REQ_MSISDN" VARCHAR2(20), 
	"CLIENT_ID" VARCHAR2(30), 
	"ACCOUNT_NO" VARCHAR2(20), 
	"ACCOUNT_EDTL" VARCHAR2(100), 
	"CUS_NAME" VARCHAR2(100), 
	"OPERATOR" VARCHAR2(30), 
	"EDTL_TOKEN" VARCHAR2(100), 
	"TRANS_TYPE" VARCHAR2(30), 
	"ACTION" VARCHAR2(100), 
	"PAYMENT_CODE" VARCHAR2(20), 
	"REQUEST_DATE" DATE NOT NULL ENABLE, 
	"RESPONSE_DATE" DATE, 
	"MODIFIED_DATE" DATE, 
	"REQUEST_CONTENT" CLOB, 
	"RESPONSE_CONTENT" CLOB, 
	"ERROR_CODE" VARCHAR2(20), 
	"ERROR_DESC" VARCHAR2(200), 
	"RESPONSE_CODE" VARCHAR2(30), 
	"RESPONSE_DESC" VARCHAR2(200), 
	"TOTAL_UNIT" NUMBER(38,5), 
	"AMOUNT" NUMBER(38,5), 
	"TOTAL_AMOUNT" NUMBER(38,5), 
	"CORRECT_CODE" VARCHAR2(3), 
	"CORRECT_SOURCE" VARCHAR2(3), 
	"CORRECT_RESPONSE_CODE" VARCHAR2(3), 
	"CORRECT_DATE" DATE, 
	"CORRECT_REASON" VARCHAR2(200), 
	"RECON_RESULT" VARCHAR2(3), 
	"MORE_DETAIL" VARCHAR2(300), 
	"FILE_IMPORT_NAME" VARCHAR2(50), 
	"INVOICE_NO" VARCHAR2(100), 
	"PAYMENT_DES" VARCHAR2(100), 
	"GROUP_TRANS_NO" VARCHAR2(20), 
	"POC_REF" NUMBER, 
	"CURRENT_BALANCE" NUMBER, 
	"CURRENT_BALANCE_BEFORE" NUMBER, 
	"CURRENT_BALANCE_AFTER" NUMBER, 
	"AVAILABLE_BALANCE" NUMBER, 
	"AVAILABLE_BALANCE_BEFORE" NUMBER, 
	"AVAILABLE_BALANCE_AFTER" NUMBER, 
	"CREDIT_LIMIT" NUMBER, 
	"EMERGENCY_CREDIT" NUMBER, 
	 CONSTRAINT "TRANS_MERCHANT_LOG_NEW_PK" PRIMARY KEY ("TRANS_MERCHANT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("REQUEST_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("RESPONSE_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

