CREATE TABLE "EWALLET_V21"."TRANSACTION_FOR_TARIFF_134262" 
   (	"ACCOUNT_ID" NUMBER, 
	"TRANSACTION_ID" NUMBER, 
	"ACTION_ID" NUMBER, 
	"PROCESS_CODE" VARCHAR2(6), 
	"TRANS_TYPE_ID" NUMBER, 
	"TRANS_AMOUNT" NUMBER, 
	"CURRENCY_CODE" VARCHAR2(6), 
	"TRANS_DATE" DATE, 
	"TRANS_DATE_INT" NUMBER, 
	"TRANS_MONTH_INT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

