CREATE TABLE "EWALLET_V21"."TRANSFER_CONFIG" 
   (	"NAME" VARCHAR2(100), 
	"CODE" VARCHAR2(20), 
	"FROM_ACC_ID" NUMBER, 
	"TO_ACC_ID" NUMBER, 
	"STATUS" NUMBER, 
	"TYPE" VARCHAR2(20), 
	"PROCESS_CODE" VARCHAR2(6), 
	"PROCESS_CODE_2" VARCHAR2(6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

