CREATE TABLE "EWALLET_V21"."TRANS_TUITION" 
   (	"ID" NUMBER(22,0), 
	"ACTION_ID" NUMBER(22,0), 
	"TRANSACTION_ID" NUMBER(22,0), 
	"STUDENT_ID" VARCHAR2(100), 
	"STUDENT_NAME" VARCHAR2(200), 
	"SCHOOL_ID" NUMBER(22,0), 
	"SCHOOL_CODE" VARCHAR2(100), 
	"TUITION_NAME" VARCHAR2(200), 
	"TRANS_TUITION_TYPE_ID" NUMBER(22,0), 
	"AMOUNT" NUMBER(22,2), 
	"STATUS" NUMBER(22,0), 
	"EXPIRED_DATE" DATE, 
	"DESCRIPTION" VARCHAR2(500), 
	"CARRIED_PHONE" VARCHAR2(20), 
	"CARRIED_NAME" VARCHAR2(100), 
	"CARRIED_CODE" VARCHAR2(100), 
	"CREATED_DATE" DATE, 
	"UPDATED_DATE" DATE, 
	"TRANS_DATE" DATE, 
	"FACULTY_CODE" VARCHAR2(100), 
	"DEPARTMENT" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

