CREATE TABLE "EWALLET_V21"."TRANS_VIEW_GROUP_CONFIG" 
   (	"VIEW_TRANS_GROUP_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"PROCESS_CODE" VARCHAR2(6), 
	"GROUP_NAME" VARCHAR2(50), 
	"SORT" NUMBER(2,0), 
	"STATUS" NUMBER(2,0), 
	"LOCALE_KEY" VARCHAR2(50), 
	"TRANS_TYPE_ID" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

