CREATE TABLE "EWALLET_V21"."TRANS_STATE" 
   (	"TRANS_STATE_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(50), 
	"DESCRIPTION" VARCHAR2(100), 
	"TRANS_STATE_GROUP_ID" NUMBER(22,0) DEFAULT 1, 
	 CONSTRAINT "TRANS_STATE_PK" PRIMARY KEY ("TRANS_STATE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

