CREATE TABLE "EWALLET_V21"."TRANS_CASH" 
   (	"ACTION_ID" NUMBER(14,0), 
	"FROM_ACCOUNT" VARCHAR2(20), 
	"TO_ACCOUNT" VARCHAR2(20), 
	"FROM_NAME" VARCHAR2(50), 
	"TO_NAME" VARCHAR2(50), 
	"TO_CURRENCY" VARCHAR2(20), 
	"ORG_CURRENCY" VARCHAR2(20), 
	"EX_RATE" NUMBER(3,2), 
	"CREATED_DATE" DATE, 
	"ACTION_STATE" NUMBER(2,0), 
	"SECRET_CODE" VARCHAR2(200), 
	"LOCK_ACTION_ID" NUMBER(14,0), 
	"REFER_ACTION_ID" NUMBER(14,0), 
	"CARRIED_ACCOUNT" NUMBER(14,0), 
	"CARRIED_NAME" VARCHAR2(100), 
	"AREA_RECEIVER" VARCHAR2(20), 
	"ADDRESS" VARCHAR2(100), 
	"PROCESS_CODE" VARCHAR2(6), 
	"LAST_MODIFIED" DATE, 
	"CARRIED_CODE" VARCHAR2(20), 
	"STAFF_CODE" VARCHAR2(20), 
	"STAFF_NAME" VARCHAR2(50), 
	"EXPIRED_DATE" DATE, 
	"AMOUNT" NUMBER(30,5), 
	"ORG_AMOUNT" NUMBER(30,5), 
	"FROM_PHONE" VARCHAR2(20), 
	"TO_PHONE" VARCHAR2(20), 
	"CONTENT" VARCHAR2(100), 
	"RE_CARRIED_ACCOUNT" NUMBER(14,0), 
	"RE_CARRIED_NAME" VARCHAR2(100), 
	"RE_STAFF_CODE" VARCHAR2(20), 
	"RE_STAFF_NAME" VARCHAR2(50), 
	"RE_CARRIED_PHONE" VARCHAR2(20), 
	"CARRIED_PHONE" VARCHAR2(20), 
	"TRANSACTION_ID" NUMBER(12,0), 
	"SOURCE_OF_FUND" VARCHAR2(100), 
	"APPROVED_DATE" DATE, 
	"FEE" NUMBER(10,0) DEFAULT 0, 
	"SECRET_CODE_TIME" DATE DEFAULT SYSDATE, 
	"OLD_SECRET_CODE" VARCHAR2(2000), 
	"REJECT_WITHDRAW_ACTION_IDS" VARCHAR2(200)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
  PARTITION BY RANGE ("CREATED_DATE") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) 
 (PARTITION "LOG_DATA_P1"  VALUES LESS THAN (TO_DATE(' 2017-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ) ;

