CREATE TABLE "EWALLET_V21"."TRANS_STATE_CONFIG" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PROCESS_CODE" VARCHAR2(6) NOT NULL ENABLE, 
	"STEP_ACCOUNTING" NUMBER(2,0) NOT NULL ENABLE, 
	"BUSINESS_STATE" NUMBER(2,0) NOT NULL ENABLE, 
	"ACCOUNTING_STATE" VARCHAR2(50) NOT NULL ENABLE, 
	"TRANS_STEP_STATE_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"TRANSACTION_STATE_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"IS_FINISHED" NUMBER(2,0) NOT NULL ENABLE, 
	"SERVICE_CODE" VARCHAR2(100), 
	"PARTNER_CODE" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 2 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

