CREATE TABLE "EWALLET_V21"."TRANS_FEE" 
   (	"ID" NUMBER, 
	"PROCESS_CODE" VARCHAR2(20), 
	"MONTHLY" NUMBER, 
	"VALUE_TYPE" NUMBER, 
	"VALUE" NUMBER, 
	"TRANSACTION_ID" NUMBER, 
	"CREATE_DATE" DATE, 
	"MODIFY_DATE" DATE, 
	"TRANSACTION_ID_REF" NUMBER, 
	"ACCOUNT_ID" NUMBER, 
	"STATUS" NUMBER, 
	"FEE_MONEY" NUMBER, 
	"REASON" VARCHAR2(1000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

