CREATE TABLE "EWALLET_V21"."TRANS_LIMIT_CONFIG" 
   (	"CONFIG_ID" NUMBER NOT NULL ENABLE, 
	"CONFIG_TYPE" VARCHAR2(20) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(100), 
	"VALUE" NUMBER, 
	"STATUS" NUMBER(1,0), 
	"VALID_FROM" DATE, 
	"VALID_TO" DATE, 
	"CREATED_BY" VARCHAR2(50), 
	"DATE_CREATED" DATE, 
	"MODIFIED_BY" VARCHAR2(50), 
	"DATE_MODIFIED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

