CREATE TABLE "EWALLET_V21"."TRANS_BCCS" 
   (	"ID" NUMBER, 
	"CHARGE_LOG_ID" NUMBER, 
	"REQUEST_ID" NUMBER NOT NULL ENABLE, 
	"TRANSACTION_ID" NUMBER, 
	"USERNAME" VARCHAR2(50), 
	"IP" VARCHAR2(50), 
	"SERVICE_CODE" VARCHAR2(100), 
	"MSISDN" VARCHAR2(20) NOT NULL ENABLE, 
	"CHARGE_TYPE" VARCHAR2(5), 
	"AMOUNT" NUMBER NOT NULL ENABLE, 
	"CHARGE_TIME" DATE, 
	"DESCRIPTION" VARCHAR2(250), 
	"ERROR_OCS" VARCHAR2(50), 
	"DURATION" NUMBER, 
	"DATE_CREATED" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"DATE_UPDATED" DATE, 
	"CHECK_RESULT" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

