CREATE TABLE "EWALLET_V21"."TRANS_FORBIDDEN_CONFIG" 
   (	"PROCESS_CODE" VARCHAR2(6) NOT NULL ENABLE, 
	"TRANS_TYPE_ID" NUMBER(8,0), 
	"TRANS_STATE_ID" NUMBER(8,0), 
	"ERROR_CODE" VARCHAR2(5)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

