CREATE TABLE "EWALLET_V21"."TRANS_PAY_KAKOAK" 
   (	"ID" NUMBER, 
	"ACCOUNT_ID" NUMBER, 
	"CUS_PHONE" VARCHAR2(15), 
	"CUS_NAME" VARCHAR2(50), 
	"AMOUNT" NUMBER(8,2), 
	"CREATE_BY" VARCHAR2(50), 
	"APPROVE_BY" VARCHAR2(50), 
	"CREATE_DATE" DATE, 
	"APPROVE_DATE" DATE, 
	"DESCRIPTION" VARCHAR2(250), 
	"STATUS" NUMBER DEFAULT 0, 
	"ERR_CODE" VARCHAR2(50), 
	"ERR_DES" VARCHAR2(1024), 
	"TRANSACTION_ID" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

