CREATE TABLE "EWALLET_V21"."UPDATE_AGENT_ACTION" 
   (	"AGENT_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"AGENT_NAME" NVARCHAR2(100) NOT NULL ENABLE, 
	"USE_BANK" NVARCHAR2(2), 
	"GENDER" NVARCHAR2(10), 
	"PAPER_TYPE" NVARCHAR2(4), 
	"PAPER_NUMBER" NVARCHAR2(20), 
	"ISSUED_DATE" DATE, 
	"EXPIRED_DATE" DATE, 
	"ISSUED_PLACE" NVARCHAR2(50), 
	"COUNTRY" NVARCHAR2(100), 
	"PROVINCE" NVARCHAR2(20), 
	"DISTRICT" NVARCHAR2(20), 
	"ADDRESS" NVARCHAR2(100), 
	"LATITUDE" NUMBER(25,20), 
	"LONGITUDE" NUMBER(25,20), 
	"PHONE" NVARCHAR2(50), 
	"STATUS" NUMBER(2,0), 
	"CREATED_DATE" DATE, 
	"CREATE_BY" NVARCHAR2(50), 
	"MODIFY_DATE" DATE, 
	"MODIFY_BY" NVARCHAR2(50), 
	"PARTY_ROLE_ID" NUMBER(12,0), 
	"CODE" VARCHAR2(30), 
	"AREA_CODE" VARCHAR2(50), 
	"BANK_ACC_NO" VARCHAR2(50), 
	"BANK_ACC_NAME" VARCHAR2(50), 
	"BANK_BRANCH" VARCHAR2(30), 
	"BANK_CODE" VARCHAR2(30), 
	"TRANSACTION_ID" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

