CREATE TABLE "EWALLET_V21"."V_ACCOUNT_STATUS_FULL_BK" 
   (	"ACCOUNT_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"PAN" VARCHAR2(34), 
	"ACTIVE_TIME" DATE, 
	"CURRENCY_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"PARTITION_KEY" VARCHAR2(2), 
	"IS_CURRENT" NUMBER(1,0), 
	"ACCOUNT_TYPE_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"ACCOUNT_STATE_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"ROLE_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"PARTY_ID" NUMBER(22,0) NOT NULL ENABLE, 
	"ROLE_NAME" VARCHAR2(50), 
	"FIRST_NAME" VARCHAR2(50), 
	"LAST_NAME" VARCHAR2(100), 
	"GENDER" NVARCHAR2(20), 
	"BIRTHDAY" DATE, 
	"PREFERRED_LANGUAGE" VARCHAR2(5), 
	"USE_BANK_ACC" NUMBER(2,0), 
	"MSISDN" VARCHAR2(20), 
	"CURRENCY_CODE" VARCHAR2(3), 
	"CURRENCY_NUM_CODE" VARCHAR2(3), 
	"PAPER_TYPE" VARCHAR2(4), 
	"PAPER_NUMBER" VARCHAR2(25) NOT NULL ENABLE, 
	"ISSUED_DATE" DATE, 
	"EXPIRED_DATE" DATE, 
	"ACCOUNT_STATE_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"ACCOUNT_TYPE_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"PARTY_ROLE_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"CURRENCY_SYMBOL" VARCHAR2(5), 
	"CURRENCY_DECIMAL" VARCHAR2(10), 
	"BALANCE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

