CREATE TABLE "EWALLET_V21"."VIEW_TRANS_GROUP" 
   (	"VIEW_TRANS_GROUP_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"PROCESS_CODE" VARCHAR2(6), 
	"GROUP_NAME" VARCHAR2(50), 
	"SORT" NUMBER(2,0), 
	"STATUS" NUMBER(2,0) DEFAULT 1, 
	"LOCALE_KEY" VARCHAR2(50)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

