CREATE TABLE "EWALLET_V21"."VIEW_TRANS_CONFIG" 
   (	"VIEW_TRANS_CONFIG_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"PROCESS_CODE" VARCHAR2(6), 
	"TABLE_NAME" VARCHAR2(200)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

