CREATE TABLE "EWALLET_V21"."WALLET_ENTITY" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"UNIQUE_ID" VARCHAR2(40), 
	"CATEGORY" VARCHAR2(30), 
	"CODE" VARCHAR2(30), 
	"ABBREVIATION" VARCHAR2(20), 
	"NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"URL" VARCHAR2(100), 
	"PATH_IMG" VARCHAR2(200), 
	"TYPE_ID" NUMBER, 
	"ACCOUNT_ID" NUMBER, 
	"TEMP_ACC_ID_IN" NUMBER, 
	"TEMP_ACC_ID_OUT" NUMBER, 
	"TOKEN" VARCHAR2(100), 
	"OPERATION_ID" VARCHAR2(40), 
	"BALANCE" NUMBER, 
	"AVAILABLE_BALANCE" NUMBER, 
	"DATE_CREATED" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(30) NOT NULL ENABLE, 
	"DATE_MODIFIED" DATE, 
	"MODIFIED_BY" VARCHAR2(30), 
	"STATUS" NUMBER NOT NULL ENABLE, 
	"NOTE" VARCHAR2(50), 
	 CONSTRAINT "WALLET_ENTITY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

