CREATE TABLE "EWALLET_V21"."WHILELIST_BUY_DATA" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"MSISDN" VARCHAR2(20) NOT NULL ENABLE, 
	"TYPE" NUMBER(1,0), 
	"CREATE_DATE" DATE, 
	"DESCRIPTION" VARCHAR2(500), 
	"STATUS" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"UPDATED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

