CREATE TABLE "EWALLET_V21"."white_list_test" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"MSISDN" VARCHAR2(20) NOT NULL ENABLE, 
	"TYPE" NUMBER(1,0), 
	"CREATE_DATE" DATE, 
	"DESCRIPTION" VARCHAR2(500), 
	"STATUS" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"UPDATED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

