
SELECT
    ID,
  ACTION_ID,
  CORE_TRANSACTION_ID,
  CREATED_DATE,
  DIRECTION,
  REF_TRANS_ID,
  REQUEST_CONTENT,
  RESPONSE_CODE,
  RESPONSE_CONTENT
FROM
    ACCESS_LOG
WHERE
    ID >= TRUNC(SYSDATE - 1)
            AND ID < TRUNC(SYSDATE)
        