SELECT
    ACCOUNT_ID ,
    PAN ,
    ACCOUNT_STATE_ID ,
    NULL AS BALANCE ,
    ACCOUNT_TYPE_ID ,
    MODIFIED_DATE ,
    CURRENCY_ID ,
    PARTY_ROLE_ID ,
    CURRENCY ,
    PARTITION_KEY ,
    NULL AS HOLDING_BALANCE ,
    NULL AS AVAILABLE_BALANCE ,
    CREATED_DATE ,
    PIN ,
    VPAN ,
    LAST_RESET_PIN ,
    IS_CURRENT ,
    COUNT_QUERY_CASH ,
    ACTIVE_TIME ,
    LAST_TRANS_TIME ,
    LAST_CHANGE_BALANCE_TIME ,
    CURRENCY_CODE ,
    RE_ACTIVE_TIME 
FROM
    ACCOUNT

