
SELECT
    ACCOUNT_ID,
  PAN,
  ACCOUNT_STATE_ID,
  NULL as BALANCE,
  ACCOUNT_TYPE_ID,
  MODIFIED_DATE,
  CURRENCY_ID,
  PARTY_ROLE_ID,
  CURRENCY,
  PARTITION_KEY,
  NULL as HOLDING_BALANCE,
  NULL as AVAILABLE_BALANCE,
  CREATED_DATE,
  PIN,
  VPAN,
  LAST_RESET_PIN,
  IS_CURRENT,
  COUNT_QUERY_CASH,
  ACTIVE_TIME,
  LAST_TRANS_TIME,
  LAST_CHANGE_BALANCE_TIME,
  CURRENCY_CODE,
  RE_ACTIVE_TIME
FROM
    ACCOUNT
WHERE
    ACCOUNT_ID >= TRUNC(SYSDATE - 1)
            AND ACCOUNT_ID < TRUNC(SYSDATE)
        