
SELECT
    ACCOUNT_RIGHT_ID,
  ACCOUNT_ID,
  ACCOUNT_STATE_ID,
  PROCESS_CODE,
  TRANSACTION_TYPE_ID,
  ACCOUNT_TYPE_ID,
  CREATED_BY,
  MODIFIED_BY,
  CREATED_TIME,
  LAST_MODIFIED,
  STATUS,
  EFFECT_TYPE,
  PARTNER_CODE,
  SERVICE_CODE
FROM
    account_right
WHERE
    ACCOUNT_RIGHT_ID >= TRUNC(SYSDATE - 1)
            AND ACCOUNT_RIGHT_ID < TRUNC(SYSDATE)
        