SELECT 
    FACT_DATE,
    ACCOUNT_ID,
    TOTAL_CREDIT,
    TOTAL_DEBIT,
    TOTAL_TRANSFER,
    TOTAL_ENQUIRY,
    TOTAL_LOGIN,
    TOTAL_TRANSFER_FAIL,
    TOTAL_TRANSFER_BLOCK,
    TOTAL_LOGIN_FAIL,
    TOTAL_ACTION,
    OPENING_BALANCE,
    CLOSING_BALANCE
FROM "TRANSACTION_FACT_DAILY" 
WHERE 
	FACT_DATE BETWEEN TRUNC(SYSDATE - 1)
				AND TRUNC(SYSDATE) - 1/86400
    and ROW_NUM <= 100;


