SELECT 
TRANS_ACCOUNTING_ID ,
TRANSACTION_ID ,
ACTION_ID ,
PROCESS_CODE ,
TRANS_TYPE_ID ,
ACTION_NODE_ID ,
FROM_ACC_ID ,
FROM_PARTY_ROLE_ID ,
TO_ACC_ID ,
TO_PARTY_ROLE_ID ,
AMOUNT ,
CURRENCY_CODE ,
DATE_CREATED ,
ACCOUNTING_TYPE_ID ,
TRANS_STATE_ID ,
STATUS ,
ERROR_CODE ,
ERROR_DES ,
TRANS_COMMISSION_ID
FROM "TRANSACTION_ACCOUNTING_PENDING" 
WHERE 
  DATE_CREATED BETWEEN TRUNC(SYSDATE - 1)
        AND TRUNC(SYSDATE) - 1/86400; 
