SELECT
  ID,
  SUM_DATE,
  ITEM_ID,
  VALUE_DAY,
  VALUE_MON,
  INSERT_DATE,
  DESCRIPTION,
  SYN_STATUS,
  SYN_DATE,
  SYN_DES
FROM
  RPT_UMONEY_SUM_BI
WHERE
  SUM_DATE BETWEEN TRUNC(SYSDATE - 1)
            AND TRUNC(SYSDATE) - 1/86400;
