SELECT
    IMEI,
    CARRIED_ACC_ID,
    TYPE,
    ERR_CODE,
    STATUS,
    DATE_CREATED,
    ERR_DES,
    BONUS_AMOUNT,
    TRANS_ID,
    ID,
    MSISDN,
    DEPOSIT_AMOUNT
FROM
    LOG_BONUS_DEPOSIT
WHERE
    DATE_CREATED BETWEEN TRUNC (SYSDATE - 1) AND TRUNC  (SYSDATE) - 1 / 86400;