
SELECT
    PARTY_ROLE_ID,
  ROLE_ID,
  VALID_FROM,
  VALID_TO,
  STATUS,
  MSISDN,
  CREATED_DATE,
  DATE_MODIFIED,
  TIER,
  LAST_PIN_CHANGED,
  PARTITION_KEY,
  PARTY_ROLE_NUMBER,
  PATH,
  PARENT_ID,
  MODIFY_BY,
  PARTY_ID,
  PARTY_PAPER_ID,
  SUB_ID,
  CUST_ID,
  SHOP_CODE,
  COMMISSION_FORWARD,
  DELEGATE_ID,
  BANK_ACCOUNT_ID
FROM
    PARTY_ROLE
WHERE
    PARTY_ROLE_ID >= TRUNC(SYSDATE - 1)
            AND PARTY_ROLE_ID < TRUNC(SYSDATE)
        