
SELECT
    TARIFF_PLAN_ID,
  ACCOUNT_ID,
  STATUS,
  VALID_FROM,
  VALID_TO,
  PLAN_NAME,
  VERSION,
  PIORITY,
  CREATED_DATE,
  CREATED_BY,
  MODIFIED_DATE,
  MODIFIED_BY
FROM
    TARIFF_PLAN_SPECIFIC
WHERE
    TARIFF_PLAN_ID >= TRUNC(SYSDATE - 1)
            AND TARIFF_PLAN_ID < TRUNC(SYSDATE)
        